"""All German settlements by population for coverage tracking.
Updated from Wikipedia: Liste der Städte in Deutschland."""

GERMAN_CITIES_BY_STATE = {'Baden-Württemberg': ['Aach',
                       'Aalen',
                       'Achern',
                       'Adelsheim',
                       'Aichtal',
                       'Albstadt',
                       'Alpirsbach',
                       'Altensteig',
                       'Asperg',
                       'Aulendorf',
                       'Backnang',
                       'Bad Buchau',
                       'Bad Dürrheim',
                       'Bad Friedrichshall',
                       'Bad Herrenalb',
                       'Bad Krozingen',
                       'Bad Liebenzell',
                       'Bad Mergentheim',
                       'Bad Rappenau',
                       'Bad Saulgau',
                       'Bad Schussenried',
                       'Bad Säckingen',
                       'Bad Teinach-Zavelstein',
                       'Bad Urach',
                       'Bad Waldsee',
                       'Bad Wildbad',
                       'Bad Wimpfen',
                       'Bad Wurzach',
                       'Baden-Baden',
                       'Balingen',
                       'Beilstein',
                       'Besigheim',
                       'Biberach an der Riß',
                       'Bietigheim-Bissingen',
                       'Blaubeuren',
                       'Blaustein',
                       'Blumberg',
                       'Bonndorf im Schwarzwald',
                       'Bopfingen',
                       'Boxberg',
                       'Brackenheim',
                       'Breisach am Rhein',
                       'Bretten',
                       'Bruchsal',
                       'Bräunlingen',
                       'Buchen (Odenwald)',
                       'Burladingen',
                       'Böblingen',
                       'Bönnigheim',
                       'Bühl',
                       'Calw',
                       'Crailsheim',
                       'Creglingen',
                       'Dietenheim',
                       'Ditzingen',
                       'Donaueschingen',
                       'Donzdorf',
                       'Dornhan',
                       'Dornstetten',
                       'Eberbach',
                       'Ebersbach an der Fils',
                       'Ehingen (Donau)',
                       'Eislingen/Fils',
                       'Ellwangen (Jagst)',
                       'Elzach',
                       'Emmendingen',
                       'Endingen am Kaiserstuhl',
                       'Engen',
                       'Eppelheim',
                       'Eppingen',
                       'Erbach',
                       'Esslingen am Neckar',
                       'Ettenheim',
                       'Ettlingen',
                       'Fellbach',
                       'Filderstadt',
                       'Forchtenberg',
                       'Freiberg am Neckar',
                       'Freiburg im Breisgau',
                       'Freudenberg',
                       'Freudenstadt',
                       'Fridingen an der Donau',
                       'Friedrichshafen',
                       'Furtwangen im Schwarzwald',
                       'Gaggenau',
                       'Gaildorf',
                       'Gammertingen',
                       'Geisingen',
                       'Geislingen',
                       'Geislingen an der Steige',
                       'Gengenbach',
                       'Gerabronn',
                       'Gerlingen',
                       'Gernsbach',
                       'Giengen an der Brenz',
                       'Großbottwar',
                       'Grünsfeld',
                       'Gundelsheim',
                       'Göppingen',
                       'Güglingen',
                       'Haigerloch',
                       'Haiterbach',
                       'Haslach im Kinzigtal',
                       'Hausach',
                       'Hayingen',
                       'Hechingen',
                       'Heidelberg',
                       'Heidenheim an der Brenz',
                       'Heilbronn',
                       'Heimsheim',
                       'Heitersheim',
                       'Hemsbach',
                       'Herbolzheim',
                       'Herbrechtingen',
                       'Herrenberg',
                       'Hettingen',
                       'Heubach',
                       'Hockenheim',
                       'Holzgerlingen',
                       'Horb am Neckar',
                       'Hornberg',
                       'Hüfingen',
                       'Ilshofen',
                       'Ingelfingen',
                       'Isny im Allgäu',
                       'Kandern',
                       'Karlsruhe',
                       'Kehl',
                       'Kenzingen',
                       'Kirchberg an der Jagst',
                       'Kirchheim unter Teck',
                       'Knittlingen',
                       'Konstanz',
                       'Korntal-Münchingen',
                       'Kornwestheim',
                       'Kraichtal',
                       'Krautheim',
                       'Kuppenheim',
                       'Külsheim',
                       'Künzelsau',
                       'Ladenburg',
                       'Lahr/Schwarzwald',
                       'Laichingen',
                       'Langenau',
                       'Langenburg',
                       'Lauchheim',
                       'Lauda-Königshofen',
                       'Laufenburg (Baden)',
                       'Lauffen am Neckar',
                       'Laupheim',
                       'Lauterstein',
                       'Leimen',
                       'Leinfelden-Echterdingen',
                       'Leingarten',
                       'Leonberg',
                       'Leutkirch im Allgäu',
                       'Lichtenau',
                       'Lorch',
                       'Ludwigsburg',
                       'Löffingen',
                       'Lörrach',
                       'Löwenstein',
                       'Mahlberg',
                       'Mannheim',
                       'Marbach am Neckar',
                       'Markdorf',
                       'Markgröningen',
                       'Maulbronn',
                       'Meersburg',
                       'Mengen',
                       'Metzingen',
                       'Meßkirch',
                       'Meßstetten',
                       'Mosbach',
                       'Munderkingen',
                       'Murrhardt',
                       'Möckmühl',
                       'Mössingen',
                       'Mühlacker',
                       'Mühlheim an der Donau',
                       'Müllheim im Markgräflerland',
                       'Münsingen',
                       'Nagold',
                       'Neckarbischofsheim',
                       'Neckargemünd',
                       'Neckarsulm',
                       'Neresheim',
                       'Neubulach',
                       'Neudenau',
                       'Neuenburg am Rhein',
                       'Neuenbürg',
                       'Neuenstadt am Kocher',
                       'Neuenstein',
                       'Neuffen',
                       'Niedernhall',
                       'Niederstetten',
                       'Niederstotzingen',
                       'Nürtingen',
                       'Oberderdingen',
                       'Oberkirch',
                       'Oberkochen',
                       'Oberndorf am Neckar',
                       'Oberriexingen',
                       'Ochsenhausen',
                       'Offenburg',
                       'Oppenau',
                       'Osterburken',
                       'Ostfildern',
                       'Owen',
                       'Pforzheim',
                       'Pfullendorf',
                       'Pfullingen',
                       'Philippsburg',
                       'Plochingen',
                       'Radolfzell am Bodensee',
                       'Rastatt',
                       'Rauenberg',
                       'Ravensburg',
                       'Ravenstein',
                       'Remseck am Neckar',
                       'Renchen',
                       'Renningen',
                       'Reutlingen',
                       'Rheinau',
                       'Rheinfelden (Baden)',
                       'Rheinstetten',
                       'Riedlingen',
                       'Rosenfeld',
                       'Rottenburg am Neckar',
                       'Rottweil',
                       'Rutesheim',
                       'Sachsenheim',
                       'Scheer',
                       'Schelklingen',
                       'Schiltach',
                       'Schopfheim',
                       'Schorndorf',
                       'Schramberg',
                       'Schriesheim',
                       'Schrozberg',
                       'Schwaigern',
                       'Schwetzingen',
                       'Schwäbisch Gmünd',
                       'Schwäbisch Hall',
                       'Schömberg',
                       'Schönau',
                       'Schönau im Schwarzwald',
                       'Sigmaringen',
                       'Sindelfingen',
                       'Singen (Hohentwiel)',
                       'Sinsheim',
                       'Spaichingen',
                       'St. Blasien',
                       'St. Georgen im Schwarzwald',
                       'Staufen im Breisgau',
                       'Steinheim an der Murr',
                       'Stockach',
                       'Stutensee',
                       'Stühlingen',
                       'Sulz am Neckar',
                       'Sulzburg',
                       'Süßen',
                       'Tamm',
                       'Tauberbischofsheim',
                       'Tengen',
                       'Tettnang',
                       'Titisee-Neustadt',
                       'Todtnau',
                       'Triberg im Schwarzwald',
                       'Trochtelfingen',
                       'Trossingen',
                       'Tuttlingen',
                       'Tübingen',
                       'Uhingen',
                       'Ulm',
                       'Vaihingen an der Enz',
                       'Vellberg',
                       'Veringenstadt',
                       'Villingen-Schwenningen',
                       'Vogtsburg im Kaiserstuhl',
                       'Vöhrenbach',
                       'Waghäusel',
                       'Waiblingen',
                       'Waibstadt',
                       'Waldenbuch',
                       'Waldenburg',
                       'Waldkirch',
                       'Waldshut-Tiengen',
                       'Walldorf',
                       'Walldürn',
                       'Wangen im Allgäu',
                       'Wehr',
                       'Weikersheim',
                       'Weil am Rhein',
                       'Weil der Stadt',
                       'Weilheim an der Teck',
                       'Weingarten',
                       'Weinheim',
                       'Weinsberg',
                       'Weinstadt',
                       'Welzheim',
                       'Wendlingen am Neckar',
                       'Wernau (Neckar)',
                       'Wertheim',
                       'Widdern',
                       'Wiesensteig',
                       'Wiesloch',
                       'Wildberg',
                       'Winnenden',
                       'Wolfach',
                       'Zell am Harmersbach',
                       'Zell im Wiesental',
                       'Öhringen',
                       'Östringen',
                       'Überlingen'],
 'Bayern': ['Abenberg',
            'Abensberg',
            'Aichach',
            'Altdorf bei Nürnberg',
            'Altötting',
            'Alzenau',
            'Amberg',
            'Amorbach',
            'Ansbach',
            'Arnstein',
            'Arzberg',
            'Aschaffenburg',
            'Aub',
            'Auerbach in der Oberpfalz',
            'Augsburg',
            'Bad Aibling',
            'Bad Berneck im Fichtelgebirge',
            'Bad Brückenau',
            'Bad Griesbach im Rottal',
            'Bad Kissingen',
            'Bad Königshofen im Grabfeld',
            'Bad Kötzting',
            'Bad Neustadt an der Saale',
            'Bad Reichenhall',
            'Bad Rodach',
            'Bad Staffelstein',
            'Bad Tölz',
            'Bad Weißenstadt',
            'Bad Windsheim',
            'Bad Wörishofen',
            'Baiersdorf',
            'Bamberg',
            'Baunach',
            'Bayreuth',
            'Beilngries',
            'Berching',
            'Betzenstein',
            'Bischofsheim in der Rhön',
            'Bobingen',
            'Bogen',
            'Buchloe',
            'Burgau',
            'Burgbernheim',
            'Burghausen',
            'Burgkunstadt',
            'Burglengenfeld',
            'Bärnau',
            'Cham',
            'Coburg',
            'Creußen',
            'Dachau',
            'Deggendorf',
            'Dettelbach',
            'Dietfurt an der Altmühl',
            'Dillingen an der Donau',
            'Dingolfing',
            'Dinkelsbühl',
            'Donauwörth',
            'Dorfen',
            'Ebermannstadt',
            'Ebern',
            'Ebersberg',
            'Eggenfelden',
            'Eibelstadt',
            'Eichstätt',
            'Ellingen',
            'Eltmann',
            'Erbendorf',
            'Erding',
            'Erlangen',
            'Erlenbach am Main',
            'Eschenbach in der Oberpfalz',
            'Feuchtwangen',
            'Fladungen',
            'Forchheim',
            'Freilassing',
            'Freising',
            'Freystadt',
            'Freyung',
            'Friedberg',
            'Furth im Wald',
            'Fürstenfeldbruck',
            'Fürth',
            'Füssen',
            'Garching bei München',
            'Gefrees',
            'Geiselhöring',
            'Geisenfeld',
            'Gemünden am Main',
            'Geretsried',
            'Germering',
            'Gerolzhofen',
            'Gersthofen',
            'Goldkronach',
            'Grafenau',
            'Grafenwöhr',
            'Grafing bei München',
            'Greding',
            'Gräfenberg',
            'Gundelfingen an der Donau',
            'Gunzenhausen',
            'Günzburg',
            'Haar',
            'Hallstadt',
            'Hammelburg',
            'Harburg (Schwaben)',
            'Hauzenberg',
            'Haßfurt',
            'Heideck',
            'Heilsbronn',
            'Helmbrechts',
            'Hemau',
            'Herrieden',
            'Hersbruck',
            'Herzogenaurach',
            'Hilpoltstein',
            'Hirschau',
            'Hof',
            'Hofheim in Unterfranken',
            'Hohenberg an der Eger',
            'Hollfeld',
            'Höchstadt an der Aisch',
            'Höchstädt an der Donau',
            'Ichenhausen',
            'Illertissen',
            'Immenstadt im Allgäu',
            'Ingolstadt',
            'Iphofen',
            'Karlstadt',
            'Kaufbeuren',
            'Kelheim',
            'Kemnath',
            'Kempten (Allgäu)',
            'Kirchenlamitz',
            'Kitzingen',
            'Klingenberg am Main',
            'Kolbermoor',
            'Kronach',
            'Krumbach (Schwaben)',
            'Kulmbach',
            'Kupferberg',
            'Königsberg in Bayern',
            'Königsbrunn',
            'Landau an der Isar',
            'Landsberg am Lech',
            'Landshut',
            'Langenzenn',
            'Lauf an der Pegnitz',
            'Laufen',
            'Lauingen (Donau)',
            'Leipheim',
            'Leutershausen',
            'Lichtenberg',
            'Lichtenfels',
            'Lindau (Bodensee)',
            'Lindenberg im Allgäu',
            'Lohr am Main',
            'Ludwigsstadt',
            'Mainbernheim',
            'Mainburg',
            'Marktbreit',
            'Marktheidenfeld',
            'Marktleuthen',
            'Marktoberdorf',
            'Marktredwitz',
            'Marktsteft',
            'Maxhütte-Haidhof',
            'Mellrichstadt',
            'Memmingen',
            'Merkendorf',
            'Miesbach',
            'Miltenberg',
            'Mindelheim',
            'Mitterteich',
            'Monheim',
            'Moosburg an der Isar',
            'Mühldorf am Inn',
            'Münchberg',
            'Münnerstadt',
            'Nabburg',
            'Naila',
            'Neu-Ulm',
            'Neuburg an der Donau',
            'Neumarkt in der Oberpfalz',
            'Neumarkt-Sankt Veit',
            'Neunburg vorm Wald',
            'Neustadt am Kulm',
            'Neustadt an der Aisch',
            'Neustadt an der Donau',
            'Neustadt an der Waldnaab',
            'Neustadt bei Coburg',
            'Neusäß',
            'Neutraubling',
            'Neuötting',
            'Nittenau',
            'Nördlingen',
            'Nürnberg',
            'Oberasbach',
            'Obernburg am Main',
            'Oberviechtach',
            'Ochsenfurt',
            'Oettingen in Bayern',
            'Olching',
            'Ornbau',
            'Osterhofen',
            'Ostheim vor der Rhön',
            'Pappenheim',
            'Parsberg',
            'Passau',
            'Pegnitz',
            'Penzberg',
            'Pfaffenhofen an der Ilm',
            'Pfarrkirchen',
            'Pfreimd',
            'Plattling',
            'Pleystein',
            'Pocking',
            'Pottenstein',
            'Pressath',
            'Prichsenstadt',
            'Puchheim',
            'Rain',
            'Regen',
            'Regensburg',
            'Rehau',
            'Riedenburg',
            'Rieneck',
            'Roding',
            'Rosenheim',
            'Roth',
            'Rothenburg ob der Tauber',
            'Rothenfels',
            'Rottenburg a.d.Laaber',
            'Rödental',
            'Röthenbach an der Pegnitz',
            'Röttingen',
            'Rötz',
            'Schauenstein',
            'Scheinfeld',
            'Scheßlitz',
            'Schillingsfürst',
            'Schlüsselfeld',
            'Schnaittenbach',
            'Schongau',
            'Schrobenhausen',
            'Schwabach',
            'Schwabmünchen',
            'Schwandorf',
            'Schwarzenbach am Wald',
            'Schwarzenbach an der Saale',
            'Schweinfurt',
            'Schönsee',
            'Schönwald',
            'Selb',
            'Selbitz',
            'Senden',
            'Seßlach',
            'Simbach am Inn',
            'Sonthofen',
            'Spalt',
            'Stadtbergen',
            'Stadtprozelten',
            'Stadtsteinach',
            'Starnberg',
            'Stein',
            'Straubing',
            'Sulzbach-Rosenberg',
            'Tegernsee',
            'Teublitz',
            'Teuschnitz',
            'Thannhausen',
            'Tirschenreuth',
            'Tittmoning',
            'Traunreut',
            'Traunstein',
            'Treuchtlingen',
            'Trostberg',
            'Töging am Inn',
            'Uffenheim',
            'Unterschleißheim',
            'Velburg',
            'Velden',
            'Viechtach',
            'Vilsbiburg',
            'Vilseck',
            'Vilshofen an der Donau',
            'Vohburg an der Donau',
            'Vohenstrauß',
            'Volkach',
            'Vöhringen',
            'Waischenfeld',
            'Waldershof',
            'Waldkirchen',
            'Waldkraiburg',
            'Waldmünchen',
            'Waldsassen',
            'Wallenfels',
            'Wasserburg am Inn',
            'Wassertrüdingen',
            'Weiden in der Oberpfalz',
            'Weilheim in Oberbayern',
            'Weismain',
            'Weißenburg in Bayern',
            'Weißenhorn',
            'Wemding',
            'Wertingen',
            'Windischeschenbach',
            'Windsbach',
            'Wolframs-Eschenbach',
            'Wolfratshausen',
            'Wunsiedel',
            'Wörth am Main',
            'Wörth an der Donau',
            'Würzburg',
            'Zeil am Main',
            'Zirndorf',
            'Zwiesel'],
 'Berlin': ['Berlin'],
 'Brandenburg': ['Altlandsberg',
                 'Angermünde',
                 'Bad Belzig',
                 'Bad Freienwalde (Oder)',
                 'Bad Liebenwerda',
                 'Bad Wilsnack',
                 'Baruth/Mark',
                 'Beelitz',
                 'Beeskow',
                 'Bernau bei Berlin',
                 'Biesenthal',
                 'Brandenburg an der Havel',
                 'Brück',
                 'Brüssow',
                 'Buckow (Märkische Schweiz)',
                 'Calau',
                 'Cottbus',
                 'Dahme/Mark',
                 'Doberlug-Kirchhain',
                 'Drebkau',
                 'Döbern',
                 'Eberswalde',
                 'Eisenhüttenstadt',
                 'Elsterwerda',
                 'Erkner',
                 'Falkenberg/Elster',
                 'Falkensee',
                 'Finsterwalde',
                 'Forst (Lausitz)',
                 'Frankfurt (Oder)',
                 'Friedland',
                 'Friesack',
                 'Fürstenberg/Havel',
                 'Fürstenwalde/Spree',
                 'Gartz (Oder)',
                 'Golßen',
                 'Gransee',
                 'Großräschen',
                 'Guben',
                 'Havelsee',
                 'Hennigsdorf',
                 'Herzberg (Elster)',
                 'Hohen Neuendorf',
                 'Joachimsthal',
                 'Jüterbog',
                 'Ketzin/Havel',
                 'Kremmen',
                 'Kyritz',
                 'Königs Wusterhausen',
                 'Lauchhammer',
                 'Lebus',
                 'Lenzen (Elbe)',
                 'Liebenwalde',
                 'Lieberose',
                 'Lindow (Mark)',
                 'Luckau',
                 'Luckenwalde',
                 'Ludwigsfelde',
                 'Lychen',
                 'Lübben (Spreewald)',
                 'Lübbenau/Spreewald',
                 'Meyenburg',
                 'Mittenwalde',
                 'Märkisch Buchholz',
                 'Mühlberg/Elbe',
                 'Müllrose',
                 'Müncheberg',
                 'Nauen',
                 'Neuruppin',
                 'Neustadt (Dosse)',
                 'Niemegk',
                 'Oderberg',
                 'Oranienburg',
                 'Ortrand',
                 'Peitz',
                 'Perleberg',
                 'Premnitz',
                 'Prenzlau',
                 'Pritzwalk',
                 'Putlitz',
                 'Rathenow',
                 'Rheinsberg',
                 'Rhinow',
                 'Ruhland',
                 'Schlieben',
                 'Schwarzheide',
                 'Schwedt/Oder',
                 'Schönewalde',
                 'Seelow',
                 'Senftenberg',
                 'Sonnewalde',
                 'Spremberg',
                 'Storkow (Mark)',
                 'Strausberg',
                 'Teltow',
                 'Templin',
                 'Teupitz',
                 'Trebbin',
                 'Treuenbrietzen',
                 'Uebigau-Wahrenbrück',
                 'Velten',
                 'Vetschau/Spreewald',
                 'Welzow',
                 'Werder (Havel)',
                 'Werneuchen',
                 'Wildau',
                 'Wittenberge',
                 'Wittstock/Dosse',
                 'Wriezen',
                 'Zehdenick',
                 'Ziesar',
                 'Zossen'],
 'Bremen': ['Bremen', 'Bremerhaven'],
 'Hamburg': ['Hamburg'],
 'Hessen': ['Allendorf (Lumda)',
            'Alsfeld',
            'Amöneburg',
            'Aßlar',
            'Babenhausen',
            'Bad Arolsen',
            'Bad Camberg',
            'Bad Hersfeld',
            'Bad Homburg vor der Höhe',
            'Bad Karlshafen',
            'Bad König',
            'Bad Nauheim',
            'Bad Orb',
            'Bad Schwalbach',
            'Bad Soden am Taunus',
            'Bad Soden-Salmünster',
            'Bad Sooden-Allendorf',
            'Bad Vilbel',
            'Bad Wildungen',
            'Battenberg (Eder)',
            'Baunatal',
            'Bebra',
            'Bensheim',
            'Biedenkopf',
            'Borken (Hessen)',
            'Braunfels',
            'Breuberg',
            'Bruchköbel',
            'Butzbach',
            'Büdingen',
            'Bürstadt',
            'Darmstadt',
            'Dieburg',
            'Diemelstadt',
            'Dietzenbach',
            'Dillenburg',
            'Dreieich',
            'Eltville am Rhein',
            'Eppstein',
            'Erbach (Odenwald)',
            'Erlensee',
            'Eschborn',
            'Eschwege',
            'Felsberg',
            'Florstadt',
            'Flörsheim am Main',
            'Frankenau',
            'Frankenberg (Eder)',
            'Frankfurt am Main',
            'Friedberg (Hessen)',
            'Friedrichsdorf',
            'Fritzlar',
            'Fulda',
            'Gedern',
            'Geisenheim',
            'Gelnhausen',
            'Gemünden (Wohra)',
            'Gernsheim',
            'Gersfeld (Rhön)',
            'Gießen',
            'Ginsheim-Gustavsburg',
            'Gladenbach',
            'Grebenau',
            'Grebenstein',
            'Griesheim',
            'Groß-Bieberau',
            'Groß-Gerau',
            'Groß-Umstadt',
            'Großalmerode',
            'Grünberg',
            'Gudensberg',
            'Hadamar',
            'Haiger',
            'Hanau',
            'Hattersheim am Main',
            'Hatzfeld (Eder)',
            'Heppenheim (Bergstraße)',
            'Herborn',
            'Herbstein',
            'Heringen (Werra)',
            'Hessisch Lichtenau',
            'Heusenstamm',
            'Hirschhorn (Neckar)',
            'Hochheim am Main',
            'Hofgeismar',
            'Hofheim am Taunus',
            'Homberg (Efze)',
            'Homberg (Ohm)',
            'Hungen',
            'Hünfeld',
            'Idstein',
            'Immenhausen',
            'Karben',
            'Kassel',
            'Kelkheim (Taunus)',
            'Kelsterbach',
            'Kirchhain',
            'Kirtorf',
            'Korbach',
            'Kronberg im Taunus',
            'Königstein im Taunus',
            'Lampertheim',
            'Langen',
            'Langenselbold',
            'Laubach',
            'Lauterbach',
            'Leun',
            'Lich',
            'Lichtenfels',
            'Liebenau',
            'Limburg an der Lahn',
            'Linden',
            'Lindenfels',
            'Lollar',
            'Lorch',
            'Lorsch',
            'Maintal',
            'Marburg',
            'Melsungen',
            'Michelstadt',
            'Mörfelden-Walldorf',
            'Mühlheim am Main',
            'Münzenberg',
            'Naumburg',
            'Neckarsteinach',
            'Neu-Anspach',
            'Neu-Isenburg',
            'Neukirchen',
            'Neustadt (Hessen)',
            'Nidda',
            'Niddatal',
            'Nidderau',
            'Niedenstein',
            'Ober-Ramstadt',
            'Obertshausen',
            'Oberursel (Taunus)',
            'Oberzent',
            'Oestrich-Winkel',
            'Offenbach am Main',
            'Ortenberg',
            'Pfungstadt',
            'Pohlheim',
            'Raunheim',
            'Rauschenberg',
            'Reichelsheim (Wetterau)',
            'Reinheim',
            'Riedstadt',
            'Rodgau',
            'Romrod',
            'Rosbach vor der Höhe',
            'Rosenthal',
            'Rotenburg an der Fulda',
            'Runkel',
            'Rödermark',
            'Rüdesheim am Rhein',
            'Rüsselsheim am Main',
            'Schlitz',
            'Schlüchtern',
            'Schotten',
            'Schwalbach am Taunus',
            'Schwalmstadt',
            'Schwarzenborn',
            'Seligenstadt',
            'Solms',
            'Sontra',
            'Spangenberg',
            'Stadtallendorf',
            'Staufenberg',
            'Steinau an der Straße',
            'Steinbach (Taunus)',
            'Tann (Rhön)',
            'Taunusstein',
            'Trendelburg',
            'Ulrichstein',
            'Usingen',
            'Vellmar',
            'Viernheim',
            'Volkmarsen',
            'Waldeck',
            'Waldkappel',
            'Wanfried',
            'Weilburg',
            'Weiterstadt',
            'Wetter (Hessen)',
            'Wetzlar',
            'Witzenhausen',
            'Wolfhagen',
            'Wächtersbach',
            'Zierenberg',
            'Zwingenberg'],
 'Mecklenburg-Vorpommern': ['Altentreptow',
                            'Anklam',
                            'Bad Doberan',
                            'Bad Sülze',
                            'Barth',
                            'Bergen auf Rügen',
                            'Boizenburg/Elbe',
                            'Brüel',
                            'Burg Stargard',
                            'Bützow',
                            'Crivitz',
                            'Dargun',
                            'Dassow',
                            'Demmin',
                            'Dömitz',
                            'Eggesin',
                            'Franzburg',
                            'Friedland',
                            'Gadebusch',
                            'Garz/Rügen',
                            'Gnoien',
                            'Goldberg',
                            'Grabow',
                            'Greifswald',
                            'Grevesmühlen',
                            'Grimmen',
                            'Güstrow',
                            'Gützkow',
                            'Hagenow',
                            'Jarmen',
                            'Klütz',
                            'Krakow am See',
                            'Kröpelin',
                            'Kühlungsborn',
                            'Laage',
                            'Lassan',
                            'Loitz',
                            'Ludwigslust',
                            'Lübtheen',
                            'Lübz',
                            'Malchin',
                            'Malchow',
                            'Marlow',
                            'Mirow',
                            'Neubrandenburg',
                            'Neubukow',
                            'Neukalen',
                            'Neukloster',
                            'Neustadt-Glewe',
                            'Neustrelitz',
                            'Parchim',
                            'Pasewalk',
                            'Penkun',
                            'Penzlin',
                            'Plau am See',
                            'Putbus',
                            'Rehna',
                            'Rerik',
                            'Ribnitz-Damgarten',
                            'Richtenberg',
                            'Rostock',
                            'Röbel/Müritz',
                            'Sassnitz',
                            'Schwaan',
                            'Schönberg',
                            'Stavenhagen',
                            'Sternberg',
                            'Stralsund',
                            'Strasburg (Uckermark)',
                            'Tessin',
                            'Teterow',
                            'Torgelow',
                            'Tribsees',
                            'Ueckermünde',
                            'Usedom',
                            'Waren (Müritz)',
                            'Warin',
                            'Wesenberg',
                            'Wismar',
                            'Wittenburg',
                            'Woldegk',
                            'Wolgast',
                            'Zarrentin am Schaalsee'],
 'Niedersachsen': ['Achim',
                   'Alfeld (Leine)',
                   'Aurich',
                   'Bad Bentheim',
                   'Bad Bevensen',
                   'Bad Fallingbostel',
                   'Bad Gandersheim',
                   'Bad Harzburg',
                   'Bad Iburg',
                   'Bad Lauterberg im Harz',
                   'Bad Münder am Deister',
                   'Bad Nenndorf',
                   'Bad Pyrmont',
                   'Bad Sachsa',
                   'Bad Salzdetfurth',
                   'Barsinghausen',
                   'Bassum',
                   'Bergen',
                   'Bersenbrück',
                   'Bleckede',
                   'Bockenem',
                   'Bodenwerder',
                   'Borkum',
                   'Brake (Unterweser)',
                   'Bramsche',
                   'Braunlage',
                   'Braunschweig',
                   'Bremervörde',
                   'Buchholz in der Nordheide',
                   'Burgdorf',
                   'Burgwedel',
                   'Buxtehude',
                   'Bückeburg',
                   'Celle',
                   'Clausthal-Zellerfeld',
                   'Cloppenburg',
                   'Cuxhaven',
                   'Damme',
                   'Dannenberg (Elbe)',
                   'Dassel',
                   'Delmenhorst',
                   'Diepholz',
                   'Dinklage',
                   'Dissen am Teutoburger Wald',
                   'Dransfeld',
                   'Duderstadt',
                   'Einbeck',
                   'Elsfleth',
                   'Elze',
                   'Emden',
                   'Eschershausen',
                   'Esens',
                   'Freren',
                   'Friesoythe',
                   'Fürstenau',
                   'Garbsen',
                   'Geestland',
                   'Gehrden',
                   'Georgsmarienhütte',
                   'Gifhorn',
                   'Goslar',
                   'Gronau (Leine)',
                   'Göttingen',
                   'Hameln',
                   'Hann. Münden',
                   'Hardegsen',
                   'Haren (Ems)',
                   'Haselünne',
                   'Helmstedt',
                   'Hemmingen',
                   'Hemmoor',
                   'Herzberg am Harz',
                   'Hessisch Oldendorf',
                   'Hildesheim',
                   'Hitzacker (Elbe)',
                   'Holzminden',
                   'Hoya',
                   'Jever',
                   'Königslutter am Elm',
                   'Laatzen',
                   'Langelsheim',
                   'Langenhagen',
                   'Leer (Ostfriesland)',
                   'Lehrte',
                   'Lingen (Ems)',
                   'Lohne (Oldenburg)',
                   'Löningen',
                   'Lüchow (Wendland)',
                   'Lüneburg',
                   'Melle',
                   'Meppen',
                   'Moringen',
                   'Munster',
                   'Neuenhaus',
                   'Neustadt am Rübenberge',
                   'Nienburg/Weser',
                   'Norden',
                   'Nordenham',
                   'Norderney',
                   'Nordhorn',
                   'Northeim',
                   'Obernkirchen',
                   'Oldenburg (Oldb)',
                   'Osnabrück',
                   'Osterholz-Scharmbeck',
                   'Osterode am Harz',
                   'Otterndorf',
                   'Papenburg',
                   'Pattensen',
                   'Peine',
                   'Quakenbrück',
                   'Rehburg-Loccum',
                   'Rethem (Aller)',
                   'Rinteln',
                   'Rodenberg',
                   'Ronnenberg',
                   'Rotenburg (Wümme)',
                   'Sachsenhagen',
                   'Salzgitter',
                   'Sarstedt',
                   'Schnackenburg',
                   'Schneverdingen',
                   'Schortens',
                   'Schöningen',
                   'Schöppenstedt',
                   'Schüttorf',
                   'Seelze',
                   'Seesen',
                   'Sehnde',
                   'Soltau',
                   'Springe',
                   'Stade',
                   'Stadthagen',
                   'Stadtoldendorf',
                   'Sulingen',
                   'Syke',
                   'Twistringen',
                   'Uelzen',
                   'Uslar',
                   'Varel',
                   'Vechta',
                   'Verden (Aller)',
                   'Visselhövede',
                   'Walsrode',
                   'Weener',
                   'Werlte',
                   'Westerstede',
                   'Wiesmoor',
                   'Wildeshausen',
                   'Wilhelmshaven',
                   'Winsen (Luhe)',
                   'Wittingen',
                   'Wittmund',
                   'Wolfenbüttel',
                   'Wolfsburg',
                   'Wunstorf',
                   'Wustrow (Wendland)',
                   'Zeven'],
 'Nordrhein-Westfalen': ['Aachen',
                         'Ahaus',
                         'Ahlen',
                         'Alsdorf',
                         'Altena',
                         'Arnsberg',
                         'Attendorn',
                         'Bad Berleburg',
                         'Bad Driburg',
                         'Bad Honnef',
                         'Bad Laasphe',
                         'Bad Lippspringe',
                         'Bad Münstereifel',
                         'Bad Oeynhausen',
                         'Bad Salzuflen',
                         'Bad Wünnenberg',
                         'Baesweiler',
                         'Balve',
                         'Barntrup',
                         'Beckum',
                         'Bedburg',
                         'Bergheim',
                         'Bergisch Gladbach',
                         'Bergkamen',
                         'Bergneustadt',
                         'Beverungen',
                         'Bielefeld',
                         'Billerbeck',
                         'Blomberg',
                         'Bocholt',
                         'Bochum',
                         'Borgentreich',
                         'Borgholzhausen',
                         'Borken',
                         'Bornheim',
                         'Bottrop',
                         'Brakel',
                         'Breckerfeld',
                         'Brilon',
                         'Brühl',
                         'Burscheid',
                         'Bünde',
                         'Büren',
                         'Castrop-Rauxel',
                         'Coesfeld',
                         'Datteln',
                         'Delbrück',
                         'Detmold',
                         'Dinslaken',
                         'Dormagen',
                         'Dorsten',
                         'Dortmund',
                         'Drensteinfurt',
                         'Drolshagen',
                         'Duisburg',
                         'Dülmen',
                         'Düren',
                         'Elsdorf',
                         'Emmerich am Rhein',
                         'Emsdetten',
                         'Enger',
                         'Ennepetal',
                         'Ennigerloh',
                         'Erftstadt',
                         'Erkelenz',
                         'Erkrath',
                         'Erwitte',
                         'Eschweiler',
                         'Espelkamp',
                         'Essen',
                         'Euskirchen',
                         'Frechen',
                         'Freudenberg',
                         'Fröndenberg/Ruhr',
                         'Geilenkirchen',
                         'Geldern',
                         'Gelsenkirchen',
                         'Gescher',
                         'Geseke',
                         'Gevelsberg',
                         'Gladbeck',
                         'Goch',
                         'Greven',
                         'Grevenbroich',
                         'Gronau (Westf.)',
                         'Gummersbach',
                         'Gütersloh',
                         'Haan',
                         'Hagen',
                         'Halle (Westf.)',
                         'Hallenberg',
                         'Haltern am See',
                         'Halver',
                         'Hamm',
                         'Hamminkeln',
                         'Harsewinkel',
                         'Hattingen',
                         'Heiligenhaus',
                         'Heimbach',
                         'Heinsberg',
                         'Hemer',
                         'Hennef (Sieg)',
                         'Herdecke',
                         'Herford',
                         'Herne',
                         'Herten',
                         'Herzogenrath',
                         'Hilchenbach',
                         'Hilden',
                         'Horn-Bad Meinberg',
                         'Horstmar',
                         'Hörstel',
                         'Höxter',
                         'Hückelhoven',
                         'Hückeswagen',
                         'Hürth',
                         'Ibbenbüren',
                         'Iserlohn',
                         'Isselburg',
                         'Jüchen',
                         'Jülich',
                         'Kaarst',
                         'Kalkar',
                         'Kamen',
                         'Kamp-Lintfort',
                         'Kempen',
                         'Kerpen',
                         'Kevelaer',
                         'Kierspe',
                         'Kleve',
                         'Korschenbroich',
                         'Krefeld',
                         'Kreuztal',
                         'Köln',
                         'Königswinter',
                         'Lage',
                         'Langenfeld (Rheinland)',
                         'Leichlingen (Rheinland)',
                         'Lemgo',
                         'Lengerich',
                         'Lennestadt',
                         'Leverkusen',
                         'Lichtenau',
                         'Linnich',
                         'Lippstadt',
                         'Lohmar',
                         'Löhne',
                         'Lübbecke',
                         'Lüdenscheid',
                         'Lüdinghausen',
                         'Lügde',
                         'Lünen',
                         'Marienmünster',
                         'Marl',
                         'Marsberg',
                         'Mechernich',
                         'Meckenheim',
                         'Medebach',
                         'Meerbusch',
                         'Meinerzhagen',
                         'Menden (Sauerland)',
                         'Meschede',
                         'Mettmann',
                         'Minden',
                         'Moers',
                         'Monheim am Rhein',
                         'Monschau',
                         'Mönchengladbach',
                         'Mülheim an der Ruhr',
                         'Münster',
                         'Netphen',
                         'Nettetal',
                         'Neuenrade',
                         'Neukirchen-Vluyn',
                         'Neuss',
                         'Nideggen',
                         'Niederkassel',
                         'Nieheim',
                         'Oberhausen',
                         'Ochtrup',
                         'Oelde',
                         'Oer-Erkenschwick',
                         'Oerlinghausen',
                         'Olfen',
                         'Olpe',
                         'Olsberg',
                         'Overath',
                         'Paderborn',
                         'Petershagen',
                         'Plettenberg',
                         'Porta Westfalica',
                         'Preußisch Oldendorf',
                         'Pulheim',
                         'Radevormwald',
                         'Rahden',
                         'Ratingen',
                         'Recklinghausen',
                         'Rees',
                         'Remscheid',
                         'Rheda-Wiedenbrück',
                         'Rhede',
                         'Rheinbach',
                         'Rheinberg',
                         'Rheine',
                         'Rietberg',
                         'Rösrath',
                         'Rüthen',
                         'Salzkotten',
                         'Sankt Augustin',
                         'Sassenberg',
                         'Schieder-Schwalenberg',
                         'Schleiden',
                         'Schloß Holte-Stukenbrock',
                         'Schmallenberg',
                         'Schwelm',
                         'Schwerte',
                         'Selm',
                         'Sendenhorst',
                         'Siegburg',
                         'Siegen',
                         'Soest',
                         'Solingen',
                         'Spenge',
                         'Sprockhövel',
                         'Stadtlohn',
                         'Steinfurt',
                         'Steinheim',
                         'Stolberg (Rheinland)',
                         'Straelen',
                         'Sundern (Sauerland)',
                         'Tecklenburg',
                         'Telgte',
                         'Troisdorf',
                         'Tönisvorst',
                         'Unna',
                         'Velbert',
                         'Velen',
                         'Verl',
                         'Versmold',
                         'Viersen',
                         'Vlotho',
                         'Voerde (Niederrhein)',
                         'Vreden',
                         'Waldbröl',
                         'Waltrop',
                         'Warburg',
                         'Warendorf',
                         'Warstein',
                         'Wassenberg',
                         'Wegberg',
                         'Werdohl',
                         'Werl',
                         'Wermelskirchen',
                         'Werne',
                         'Werther (Westf.)',
                         'Wesel',
                         'Wesseling',
                         'Wetter (Ruhr)',
                         'Wiehl',
                         'Willebadessen',
                         'Willich',
                         'Winterberg',
                         'Wipperfürth',
                         'Witten',
                         'Wuppertal',
                         'Wülfrath',
                         'Würselen',
                         'Xanten',
                         'Zülpich',
                         'Übach-Palenberg'],
 'Rheinland-Pfalz': ['Adenau',
                     'Altenkirchen (Westerwald)',
                     'Alzey',
                     'Andernach',
                     'Annweiler am Trifels',
                     'Bacharach',
                     'Bad Bergzabern',
                     'Bad Breisig',
                     'Bad Dürkheim',
                     'Bad Ems',
                     'Bad Hönningen',
                     'Bad Kreuznach',
                     'Bad Marienberg (Westerwald)',
                     'Bad Neuenahr-Ahrweiler',
                     'Bad Sobernheim',
                     'Baumholder',
                     'Bendorf',
                     'Bernkastel-Kues',
                     'Betzdorf',
                     'Bingen am Rhein',
                     'Birkenfeld',
                     'Bitburg',
                     'Boppard',
                     'Braubach',
                     'Cochem',
                     'Daaden',
                     'Dahn',
                     'Daun',
                     'Deidesheim',
                     'Dierdorf',
                     'Diez',
                     'Edenkoben',
                     'Eisenberg (Pfalz)',
                     'Emmelshausen',
                     'Frankenthal (Pfalz)',
                     'Freinsheim',
                     'Gau-Algesheim',
                     'Germersheim',
                     'Gerolstein',
                     'Grünstadt',
                     'Hachenburg',
                     'Hagenbach',
                     'Herdorf',
                     'Hermeskeil',
                     'Hillesheim',
                     'Hornbach',
                     'Höhr-Grenzhausen',
                     'Idar-Oberstein',
                     'Ingelheim am Rhein',
                     'Kaisersesch',
                     'Kaiserslautern',
                     'Kandel',
                     'Kastellaun',
                     'Katzenelnbogen',
                     'Kaub',
                     'Kirchberg (Hunsrück)',
                     'Kirchen (Sieg)',
                     'Kirchheimbolanden',
                     'Kirn',
                     'Koblenz',
                     'Konz',
                     'Kusel',
                     'Kyllburg',
                     'Lahnstein',
                     'Lambrecht (Pfalz)',
                     'Landau in der Pfalz',
                     'Landstuhl',
                     'Lauterecken',
                     'Linz am Rhein',
                     'Ludwigshafen am Rhein',
                     'Manderscheid',
                     'Mayen',
                     'Meisenheim',
                     'Mendig',
                     'Montabaur',
                     'Mülheim-Kärlich',
                     'Münstermaifeld',
                     'Nassau',
                     'Nastätten',
                     'Neuerburg',
                     'Neustadt an der Weinstraße',
                     'Neuwied',
                     'Nieder-Olm',
                     'Nierstein',
                     'Obermoschel',
                     'Oberwesel',
                     'Oppenheim',
                     'Osthofen',
                     'Otterberg',
                     'Pirmasens',
                     'Polch',
                     'Prüm',
                     'Ramstein-Miesenbach',
                     'Ransbach-Baumbach',
                     'Remagen',
                     'Rennerod',
                     'Rheinböllen',
                     'Rhens',
                     'Rockenhausen',
                     'Rodalben',
                     'Saarburg',
                     'Sankt Goar',
                     'Sankt Goarshausen',
                     'Schifferstadt',
                     'Schweich',
                     'Selters (Westerwald)',
                     'Simmern/Hunsrück',
                     'Sinzig',
                     'Speicher',
                     'Speyer',
                     'Stromberg',
                     'Traben-Trarbach',
                     'Trier',
                     'Ulmen',
                     'Unkel',
                     'Vallendar',
                     'Wachenheim an der Weinstraße',
                     'Waldmohr',
                     'Weißenthurm',
                     'Westerburg',
                     'Wirges',
                     'Wissen',
                     'Wittlich',
                     'Wolfstein',
                     'Worms',
                     'Wörrstadt',
                     'Wörth am Rhein',
                     'Zell (Mosel)',
                     'Zweibrücken'],
 'Saarland': ['Bexbach',
              'Blieskastel',
              'Dillingen/Saar',
              'Friedrichsthal',
              'Homburg',
              'Lebach',
              'Merzig',
              'Neunkirchen',
              'Ottweiler',
              'Püttlingen',
              'Saarlouis',
              'St. Ingbert',
              'St. Wendel',
              'Sulzbach/Saar',
              'Völklingen',
              'Wadern'],
 'Sachsen': ['Adorf/Vogtl.',
             'Altenberg',
             'Annaberg-Buchholz',
             'Aue-Bad Schlema',
             'Auerbach/Vogtl.',
             'Augustusburg',
             'Bad Düben',
             'Bad Elster',
             'Bad Gottleuba-Berggießhübel',
             'Bad Lausick',
             'Bad Muskau',
             'Bad Schandau',
             'Bautzen',
             'Belgern-Schildau',
             'Bernsdorf',
             'Bernstadt a. d. Eigen',
             'Bischofswerda',
             'Borna',
             'Brand-Erbisdorf',
             'Brandis',
             'Burgstädt',
             'Böhlen',
             'Chemnitz',
             'Colditz',
             'Coswig',
             'Crimmitschau',
             'Dahlen',
             'Delitzsch',
             'Dippoldiswalde',
             'Dohna',
             'Dommitzsch',
             'Döbeln',
             'Ebersbach-Neugersdorf',
             'Ehrenfriedersdorf',
             'Eibenstock',
             'Eilenburg',
             'Elsterberg',
             'Elstra',
             'Elterlein',
             'Falkenstein/Vogtl.',
             'Flöha',
             'Frankenberg/Sachsen',
             'Frauenstein',
             'Freiberg',
             'Freital',
             'Frohburg',
             'Geithain',
             'Geringswalde',
             'Geyer',
             'Glashütte',
             'Glauchau',
             'Grimma',
             'Groitzsch',
             'Großenhain',
             'Großröhrsdorf',
             'Großschirma',
             'Gröditz',
             'Grünhain-Beierfeld',
             'Görlitz',
             'Hainichen',
             'Hartenstein',
             'Hartha',
             'Heidenau',
             'Herrnhut',
             'Hohenstein-Ernstthal',
             'Hohnstein',
             'Hoyerswerda',
             'Johanngeorgenstadt',
             'Jöhstadt',
             'Kamenz',
             'Kirchberg',
             'Kitzscher',
             'Klingenthal',
             'Königsbrück',
             'Königstein (Sächsische Schweiz)',
             'Lauta',
             'Lauter-Bernsbach',
             'Leipzig',
             'Leisnig',
             'Lengenfeld',
             'Lichtenstein/Sa.',
             'Liebstadt',
             'Limbach-Oberfrohna',
             'Lommatzsch',
             'Lugau',
             'Lunzenau',
             'Löbau',
             'Lößnitz',
             'Marienberg',
             'Markkleeberg',
             'Markneukirchen',
             'Markranstädt',
             'Meerane',
             'Meißen',
             'Mittweida',
             'Mügeln',
             'Naunhof',
             'Netzschkau',
             'Neusalza-Spremberg',
             'Neustadt in Sachsen',
             'Niesky',
             'Nossen',
             'Oberlungwitz',
             'Oberwiesenthal',
             'Oederan',
             'Oelsnitz/Erzgeb.',
             'Oelsnitz/Vogtl.',
             'Olbernhau',
             'Oschatz',
             'Ostritz',
             'Pausa-Mühltroff',
             'Pegau',
             'Penig',
             'Pirna',
             'Plauen',
             'Pockau-Lengefeld',
             'Pulsnitz',
             'Rabenau',
             'Radeberg',
             'Radebeul',
             'Radeburg',
             'Regis-Breitingen',
             'Reichenbach im Vogtland',
             'Reichenbach/O.L.',
             'Riesa',
             'Rochlitz',
             'Rodewisch',
             'Rothenburg/O.L.',
             'Roßwein',
             'Rötha',
             'Sayda',
             'Scheibenberg',
             'Schirgiswalde-Kirschau',
             'Schkeuditz',
             'Schlettau',
             'Schneeberg',
             'Schwarzenberg/Erzgeb.',
             'Schöneck/Vogtl.',
             'Sebnitz',
             'Seifhennersdorf',
             'Stadt Wehlen',
             'Stollberg/Erzgeb.',
             'Stolpen',
             'Strehla',
             'Taucha',
             'Thalheim/Erzgeb.',
             'Tharandt',
             'Thum',
             'Torgau',
             'Trebsen/Mulde',
             'Treuen',
             'Waldenburg',
             'Waldheim',
             'Weißenberg',
             'Weißwasser/O.L.',
             'Werdau',
             'Wildenfels',
             'Wilkau-Haßlau',
             'Wilsdruff',
             'Wilthen',
             'Wittichenau',
             'Wolkenstein',
             'Wurzen',
             'Zittau',
             'Zschopau',
             'Zwenkau',
             'Zwickau',
             'Zwönitz'],
 'Sachsen-Anhalt': ['Aken (Elbe)',
                    'Allstedt',
                    'Alsleben (Saale)',
                    'Annaburg',
                    'Arendsee (Altmark)',
                    'Arneburg',
                    'Arnstein',
                    'Aschersleben',
                    'Bad Bibra',
                    'Bad Dürrenberg',
                    'Bad Lauchstädt',
                    'Bad Schmiedeberg',
                    'Ballenstedt',
                    'Barby',
                    'Bernburg (Saale)',
                    'Bismark (Altmark)',
                    'Bitterfeld-Wolfen',
                    'Blankenburg (Harz)',
                    'Braunsbedra',
                    'Burg',
                    'Calbe (Saale)',
                    'Coswig (Anhalt)',
                    'Dessau-Roßlau',
                    'Eckartsberga',
                    'Egeln',
                    'Eisleben',
                    'Falkenstein/Harz',
                    'Freyburg (Unstrut)',
                    'Gardelegen',
                    'Genthin',
                    'Gerbstedt',
                    'Gommern',
                    'Gräfenhainichen',
                    'Gröningen',
                    'Güsten',
                    'Halberstadt',
                    'Haldensleben',
                    'Halle (Saale)',
                    'Harzgerode',
                    'Havelberg',
                    'Hecklingen',
                    'Hettstedt',
                    'Hohenmölsen',
                    'Ilsenburg (Harz)',
                    'Jerichow',
                    'Jessen (Elster)',
                    'Kalbe (Milde)',
                    'Kelbra (Kyffhäuser)',
                    'Kemberg',
                    'Klötze',
                    'Kroppenstedt',
                    'Könnern',
                    'Köthen (Anhalt)',
                    'Landsberg',
                    'Laucha an der Unstrut',
                    'Leuna',
                    'Lützen',
                    'Mansfeld',
                    'Merseburg',
                    'Möckern',
                    'Mücheln (Geiseltal)',
                    'Naumburg (Saale)',
                    'Nebra (Unstrut)',
                    'Nienburg (Saale)',
                    'Oberharz am Brocken',
                    'Oebisfelde-Weferlingen',
                    'Oranienbaum-Wörlitz',
                    'Oschersleben (Bode)',
                    'Osterburg (Altmark)',
                    'Osterfeld',
                    'Osterwieck',
                    'Quedlinburg',
                    'Querfurt',
                    'Raguhn-Jeßnitz',
                    'Salzwedel',
                    'Sandau (Elbe)',
                    'Sandersdorf-Brehna',
                    'Sangerhausen',
                    'Schraplau',
                    'Schwanebeck',
                    'Schönebeck (Elbe)',
                    'Seehausen (Altmark)',
                    'Seeland',
                    'Staßfurt',
                    'Stendal',
                    'Stößen',
                    'Südliches Anhalt',
                    'Tangerhütte',
                    'Tangermünde',
                    'Teuchern',
                    'Thale',
                    'Wanzleben-Börde',
                    'Wegeleben',
                    'Weißenfels',
                    'Werben (Elbe)',
                    'Wernigerode',
                    'Wettin-Löbejün',
                    'Wittenberg',
                    'Wolmirstedt',
                    'Zahna-Elster',
                    'Zeitz',
                    'Zerbst/Anhalt',
                    'Zörbig'],
 'Schleswig-Holstein': ['Ahrensburg',
                        'Arnis',
                        'Bad Bramstedt',
                        'Bad Oldesloe',
                        'Bad Schwartau',
                        'Bad Segeberg',
                        'Bargteheide',
                        'Barmstedt',
                        'Bredstedt',
                        'Brunsbüttel',
                        'Büdelsdorf',
                        'Eckernförde',
                        'Elmshorn',
                        'Eutin',
                        'Fehmarn',
                        'Flensburg',
                        'Friedrichstadt',
                        'Garding',
                        'Geesthacht',
                        'Glinde',
                        'Glücksburg (Ostsee)',
                        'Glückstadt',
                        'Heide',
                        'Heiligenhafen',
                        'Husum',
                        'Itzehoe',
                        'Kaltenkirchen',
                        'Kappeln',
                        'Kellinghusen',
                        'Krempe',
                        'Lauenburg/Elbe',
                        'Lübeck',
                        'Lütjenburg',
                        'Marne',
                        'Meldorf',
                        'Mölln',
                        'Neumünster',
                        'Neustadt in Holstein',
                        'Niebüll',
                        'Norderstedt',
                        'Nortorf',
                        'Oldenburg in Holstein',
                        'Pinneberg',
                        'Plön',
                        'Preetz',
                        'Quickborn',
                        'Ratzeburg',
                        'Reinbek',
                        'Reinfeld (Holstein)',
                        'Rendsburg',
                        'Schenefeld',
                        'Schleswig',
                        'Schwarzenbek',
                        'Schwentinental',
                        'Tornesch',
                        'Tönning',
                        'Uetersen',
                        'Wahlstedt',
                        'Wedel',
                        'Wesselburen',
                        'Wilster',
                        'Wyk auf Föhr'],
 'Thüringen': ['Altenburg',
               'Amt Creuzburg',
               'An der Schmücke',
               'Apolda',
               'Arnstadt',
               'Artern',
               'Auma-Weidatal',
               'Bad Berka',
               'Bad Blankenburg',
               'Bad Frankenhausen/Kyffhäuser',
               'Bad Köstritz',
               'Bad Langensalza',
               'Bad Liebenstein',
               'Bad Lobenstein',
               'Bad Salzungen',
               'Bad Sulza',
               'Bad Tennstedt',
               'Berga-Wünschendorf',
               'Blankenhain',
               'Bleicherode',
               'Brotterode-Trusetal',
               'Bürgel',
               'Clingen',
               'Dingelstädt',
               'Dornburg-Camburg',
               'Ebeleben',
               'Eisenach',
               'Eisenberg',
               'Eisfeld',
               'Ellrich',
               'Friedrichroda',
               'Gebesee',
               'Gefell',
               'Geisa',
               'Gera',
               'Gotha',
               'Greiz',
               'Greußen',
               'Großbreitenbach',
               'Gräfenthal',
               'Gößnitz',
               'Heilbad Heiligenstadt',
               'Heldburg',
               'Heringen/Helme',
               'Hermsdorf',
               'Hildburghausen',
               'Hirschberg',
               'Hohenleuben',
               'Ilmenau',
               'Jena',
               'Kahla',
               'Kaltennordheim',
               'Kranichfeld',
               'Kölleda',
               'Königsee',
               'Lauscha',
               'Lehesten',
               'Leinefelde-Worbis',
               'Leutenberg',
               'Lucka',
               'Magdala',
               'Meiningen',
               'Meuselwitz',
               'Mühlhausen/Thüringen',
               'Münchenbernsdorf',
               'Neuhaus am Rennweg',
               'Neumark',
               'Neustadt an der Orla',
               'Nordhausen',
               'Nottertal-Heilinger Höhen',
               'Oberhof',
               'Ohrdruf',
               'Orlamünde',
               'Plaue',
               'Pößneck',
               'Ranis',
               'Rastenberg',
               'Ronneburg',
               'Roßleben-Wiehe',
               'Rudolstadt',
               'Ruhla',
               'Römhild',
               'Saalburg-Ebersdorf',
               'Saalfeld/Saale',
               'Schalkau',
               'Schkölen',
               'Schleiz',
               'Schleusingen',
               'Schmalkalden',
               'Schmölln',
               'Schwarzatal',
               'Sondershausen',
               'Sonneberg',
               'Stadtilm',
               'Stadtroda',
               'Steinach',
               'Steinbach-Hallenberg',
               'Suhl',
               'Sömmerda',
               'Tambach-Dietharz',
               'Tanna',
               'Themar',
               'Treffurt',
               'Triptis',
               'Ummerstadt',
               'Vacha',
               'Waltershausen',
               'Wasungen',
               'Weida',
               'Weimar',
               'Weißensee',
               'Werra-Suhl-Tal',
               'Wurzbach',
               'Zella-Mehlis',
               'Zeulenroda-Triebes',
               'Ziegenrück']}

ALL_CITIES = ['Aach',
 'Aachen',
 'Aalen',
 'Abenberg',
 'Abensberg',
 'Achern',
 'Achim',
 'Adelsheim',
 'Adenau',
 'Adorf/Vogtl.',
 'Ahaus',
 'Ahlen',
 'Ahrensburg',
 'Aichach',
 'Aichtal',
 'Aken (Elbe)',
 'Albstadt',
 'Alfeld (Leine)',
 'Allendorf (Lumda)',
 'Allstedt',
 'Alpirsbach',
 'Alsdorf',
 'Alsfeld',
 'Alsleben (Saale)',
 'Altdorf bei Nürnberg',
 'Altena',
 'Altenberg',
 'Altenburg',
 'Altenkirchen (Westerwald)',
 'Altensteig',
 'Altentreptow',
 'Altlandsberg',
 'Altötting',
 'Alzenau',
 'Alzey',
 'Amberg',
 'Amorbach',
 'Amt Creuzburg',
 'Amöneburg',
 'An der Schmücke',
 'Andernach',
 'Angermünde',
 'Anklam',
 'Annaberg-Buchholz',
 'Annaburg',
 'Annweiler am Trifels',
 'Ansbach',
 'Apolda',
 'Arendsee (Altmark)',
 'Arneburg',
 'Arnis',
 'Arnsberg',
 'Arnstadt',
 'Arnstein',
 'Artern',
 'Arzberg',
 'Aschaffenburg',
 'Aschersleben',
 'Asperg',
 'Attendorn',
 'Aub',
 'Aue-Bad Schlema',
 'Auerbach in der Oberpfalz',
 'Auerbach/Vogtl.',
 'Augsburg',
 'Augustusburg',
 'Aulendorf',
 'Auma-Weidatal',
 'Aurich',
 'Aßlar',
 'Babenhausen',
 'Bacharach',
 'Backnang',
 'Bad Aibling',
 'Bad Arolsen',
 'Bad Belzig',
 'Bad Bentheim',
 'Bad Bergzabern',
 'Bad Berka',
 'Bad Berleburg',
 'Bad Berneck im Fichtelgebirge',
 'Bad Bevensen',
 'Bad Bibra',
 'Bad Blankenburg',
 'Bad Bramstedt',
 'Bad Breisig',
 'Bad Brückenau',
 'Bad Buchau',
 'Bad Camberg',
 'Bad Doberan',
 'Bad Driburg',
 'Bad Düben',
 'Bad Dürkheim',
 'Bad Dürrenberg',
 'Bad Dürrheim',
 'Bad Elster',
 'Bad Ems',
 'Bad Fallingbostel',
 'Bad Frankenhausen/Kyffhäuser',
 'Bad Freienwalde (Oder)',
 'Bad Friedrichshall',
 'Bad Gandersheim',
 'Bad Gottleuba-Berggießhübel',
 'Bad Griesbach im Rottal',
 'Bad Harzburg',
 'Bad Herrenalb',
 'Bad Hersfeld',
 'Bad Homburg vor der Höhe',
 'Bad Honnef',
 'Bad Hönningen',
 'Bad Iburg',
 'Bad Karlshafen',
 'Bad Kissingen',
 'Bad Kreuznach',
 'Bad Krozingen',
 'Bad König',
 'Bad Königshofen im Grabfeld',
 'Bad Köstritz',
 'Bad Kötzting',
 'Bad Laasphe',
 'Bad Langensalza',
 'Bad Lauchstädt',
 'Bad Lausick',
 'Bad Lauterberg im Harz',
 'Bad Liebenstein',
 'Bad Liebenwerda',
 'Bad Liebenzell',
 'Bad Lippspringe',
 'Bad Lobenstein',
 'Bad Marienberg (Westerwald)',
 'Bad Mergentheim',
 'Bad Muskau',
 'Bad Münder am Deister',
 'Bad Münstereifel',
 'Bad Nauheim',
 'Bad Nenndorf',
 'Bad Neuenahr-Ahrweiler',
 'Bad Neustadt an der Saale',
 'Bad Oeynhausen',
 'Bad Oldesloe',
 'Bad Orb',
 'Bad Pyrmont',
 'Bad Rappenau',
 'Bad Reichenhall',
 'Bad Rodach',
 'Bad Sachsa',
 'Bad Salzdetfurth',
 'Bad Salzuflen',
 'Bad Salzungen',
 'Bad Saulgau',
 'Bad Schandau',
 'Bad Schmiedeberg',
 'Bad Schussenried',
 'Bad Schwalbach',
 'Bad Schwartau',
 'Bad Segeberg',
 'Bad Sobernheim',
 'Bad Soden am Taunus',
 'Bad Soden-Salmünster',
 'Bad Sooden-Allendorf',
 'Bad Staffelstein',
 'Bad Sulza',
 'Bad Säckingen',
 'Bad Sülze',
 'Bad Teinach-Zavelstein',
 'Bad Tennstedt',
 'Bad Tölz',
 'Bad Urach',
 'Bad Vilbel',
 'Bad Waldsee',
 'Bad Weißenstadt',
 'Bad Wildbad',
 'Bad Wildungen',
 'Bad Wilsnack',
 'Bad Wimpfen',
 'Bad Windsheim',
 'Bad Wurzach',
 'Bad Wörishofen',
 'Bad Wünnenberg',
 'Baden-Baden',
 'Baesweiler',
 'Baiersdorf',
 'Balingen',
 'Ballenstedt',
 'Balve',
 'Bamberg',
 'Barby',
 'Bargteheide',
 'Barmstedt',
 'Barntrup',
 'Barsinghausen',
 'Barth',
 'Baruth/Mark',
 'Bassum',
 'Battenberg (Eder)',
 'Baumholder',
 'Baunach',
 'Baunatal',
 'Bautzen',
 'Bayreuth',
 'Bebra',
 'Beckum',
 'Bedburg',
 'Beelitz',
 'Beeskow',
 'Beilngries',
 'Beilstein',
 'Belgern-Schildau',
 'Bendorf',
 'Bensheim',
 'Berching',
 'Berga-Wünschendorf',
 'Bergen',
 'Bergen auf Rügen',
 'Bergheim',
 'Bergisch Gladbach',
 'Bergkamen',
 'Bergneustadt',
 'Berlin',
 'Bernau bei Berlin',
 'Bernburg (Saale)',
 'Bernkastel-Kues',
 'Bernsdorf',
 'Bernstadt a. d. Eigen',
 'Bersenbrück',
 'Besigheim',
 'Betzdorf',
 'Betzenstein',
 'Beverungen',
 'Bexbach',
 'Biberach an der Riß',
 'Biedenkopf',
 'Bielefeld',
 'Biesenthal',
 'Bietigheim-Bissingen',
 'Billerbeck',
 'Bingen am Rhein',
 'Birkenfeld',
 'Bischofsheim in der Rhön',
 'Bischofswerda',
 'Bismark (Altmark)',
 'Bitburg',
 'Bitterfeld-Wolfen',
 'Blankenburg (Harz)',
 'Blankenhain',
 'Blaubeuren',
 'Blaustein',
 'Bleckede',
 'Bleicherode',
 'Blieskastel',
 'Blomberg',
 'Blumberg',
 'Bobingen',
 'Bocholt',
 'Bochum',
 'Bockenem',
 'Bodenwerder',
 'Bogen',
 'Boizenburg/Elbe',
 'Bonndorf im Schwarzwald',
 'Bopfingen',
 'Boppard',
 'Borgentreich',
 'Borgholzhausen',
 'Borken',
 'Borken (Hessen)',
 'Borkum',
 'Borna',
 'Bornheim',
 'Bottrop',
 'Boxberg',
 'Brackenheim',
 'Brake (Unterweser)',
 'Brakel',
 'Bramsche',
 'Brand-Erbisdorf',
 'Brandenburg an der Havel',
 'Brandis',
 'Braubach',
 'Braunfels',
 'Braunlage',
 'Braunsbedra',
 'Braunschweig',
 'Breckerfeld',
 'Bredstedt',
 'Breisach am Rhein',
 'Bremen',
 'Bremerhaven',
 'Bremervörde',
 'Bretten',
 'Breuberg',
 'Brilon',
 'Brotterode-Trusetal',
 'Bruchköbel',
 'Bruchsal',
 'Brunsbüttel',
 'Bräunlingen',
 'Brück',
 'Brüel',
 'Brühl',
 'Brüssow',
 'Buchen (Odenwald)',
 'Buchholz in der Nordheide',
 'Buchloe',
 'Buckow (Märkische Schweiz)',
 'Burg',
 'Burg Stargard',
 'Burgau',
 'Burgbernheim',
 'Burgdorf',
 'Burghausen',
 'Burgkunstadt',
 'Burglengenfeld',
 'Burgstädt',
 'Burgwedel',
 'Burladingen',
 'Burscheid',
 'Butzbach',
 'Buxtehude',
 'Bärnau',
 'Böblingen',
 'Böhlen',
 'Bönnigheim',
 'Bückeburg',
 'Büdelsdorf',
 'Büdingen',
 'Bühl',
 'Bünde',
 'Büren',
 'Bürgel',
 'Bürstadt',
 'Bützow',
 'Calau',
 'Calbe (Saale)',
 'Calw',
 'Castrop-Rauxel',
 'Celle',
 'Cham',
 'Chemnitz',
 'Clausthal-Zellerfeld',
 'Clingen',
 'Cloppenburg',
 'Coburg',
 'Cochem',
 'Coesfeld',
 'Colditz',
 'Coswig',
 'Coswig (Anhalt)',
 'Cottbus',
 'Crailsheim',
 'Creglingen',
 'Creußen',
 'Crimmitschau',
 'Crivitz',
 'Cuxhaven',
 'Daaden',
 'Dachau',
 'Dahlen',
 'Dahme/Mark',
 'Dahn',
 'Damme',
 'Dannenberg (Elbe)',
 'Dargun',
 'Darmstadt',
 'Dassel',
 'Dassow',
 'Datteln',
 'Daun',
 'Deggendorf',
 'Deidesheim',
 'Delbrück',
 'Delitzsch',
 'Delmenhorst',
 'Demmin',
 'Dessau-Roßlau',
 'Detmold',
 'Dettelbach',
 'Dieburg',
 'Diemelstadt',
 'Diepholz',
 'Dierdorf',
 'Dietenheim',
 'Dietfurt an der Altmühl',
 'Dietzenbach',
 'Diez',
 'Dillenburg',
 'Dillingen an der Donau',
 'Dillingen/Saar',
 'Dingelstädt',
 'Dingolfing',
 'Dinkelsbühl',
 'Dinklage',
 'Dinslaken',
 'Dippoldiswalde',
 'Dissen am Teutoburger Wald',
 'Ditzingen',
 'Doberlug-Kirchhain',
 'Dohna',
 'Dommitzsch',
 'Donaueschingen',
 'Donauwörth',
 'Donzdorf',
 'Dorfen',
 'Dormagen',
 'Dornburg-Camburg',
 'Dornhan',
 'Dornstetten',
 'Dorsten',
 'Dortmund',
 'Dransfeld',
 'Drebkau',
 'Dreieich',
 'Drensteinfurt',
 'Drolshagen',
 'Duderstadt',
 'Duisburg',
 'Döbeln',
 'Döbern',
 'Dömitz',
 'Dülmen',
 'Düren',
 'Ebeleben',
 'Eberbach',
 'Ebermannstadt',
 'Ebern',
 'Ebersbach an der Fils',
 'Ebersbach-Neugersdorf',
 'Ebersberg',
 'Eberswalde',
 'Eckartsberga',
 'Eckernförde',
 'Edenkoben',
 'Egeln',
 'Eggenfelden',
 'Eggesin',
 'Ehingen (Donau)',
 'Ehrenfriedersdorf',
 'Eibelstadt',
 'Eibenstock',
 'Eichstätt',
 'Eilenburg',
 'Einbeck',
 'Eisenach',
 'Eisenberg',
 'Eisenberg (Pfalz)',
 'Eisenhüttenstadt',
 'Eisfeld',
 'Eisleben',
 'Eislingen/Fils',
 'Ellingen',
 'Ellrich',
 'Ellwangen (Jagst)',
 'Elmshorn',
 'Elsdorf',
 'Elsfleth',
 'Elsterberg',
 'Elsterwerda',
 'Elstra',
 'Elterlein',
 'Eltmann',
 'Eltville am Rhein',
 'Elzach',
 'Elze',
 'Emden',
 'Emmelshausen',
 'Emmendingen',
 'Emmerich am Rhein',
 'Emsdetten',
 'Endingen am Kaiserstuhl',
 'Engen',
 'Enger',
 'Ennepetal',
 'Ennigerloh',
 'Eppelheim',
 'Eppingen',
 'Eppstein',
 'Erbach',
 'Erbach (Odenwald)',
 'Erbendorf',
 'Erding',
 'Erftstadt',
 'Erkelenz',
 'Erkner',
 'Erkrath',
 'Erlangen',
 'Erlenbach am Main',
 'Erlensee',
 'Erwitte',
 'Eschborn',
 'Eschenbach in der Oberpfalz',
 'Eschershausen',
 'Eschwege',
 'Eschweiler',
 'Esens',
 'Espelkamp',
 'Essen',
 'Esslingen am Neckar',
 'Ettenheim',
 'Ettlingen',
 'Euskirchen',
 'Eutin',
 'Falkenberg/Elster',
 'Falkensee',
 'Falkenstein/Harz',
 'Falkenstein/Vogtl.',
 'Fehmarn',
 'Fellbach',
 'Felsberg',
 'Feuchtwangen',
 'Filderstadt',
 'Finsterwalde',
 'Fladungen',
 'Flensburg',
 'Florstadt',
 'Flöha',
 'Flörsheim am Main',
 'Forchheim',
 'Forchtenberg',
 'Forst (Lausitz)',
 'Frankenau',
 'Frankenberg (Eder)',
 'Frankenberg/Sachsen',
 'Frankenthal (Pfalz)',
 'Frankfurt (Oder)',
 'Frankfurt am Main',
 'Franzburg',
 'Frauenstein',
 'Frechen',
 'Freiberg',
 'Freiberg am Neckar',
 'Freiburg im Breisgau',
 'Freilassing',
 'Freinsheim',
 'Freising',
 'Freital',
 'Freren',
 'Freudenberg',
 'Freudenstadt',
 'Freyburg (Unstrut)',
 'Freystadt',
 'Freyung',
 'Fridingen an der Donau',
 'Friedberg',
 'Friedberg (Hessen)',
 'Friedland',
 'Friedrichroda',
 'Friedrichsdorf',
 'Friedrichshafen',
 'Friedrichstadt',
 'Friedrichsthal',
 'Friesack',
 'Friesoythe',
 'Fritzlar',
 'Frohburg',
 'Fröndenberg/Ruhr',
 'Fulda',
 'Furth im Wald',
 'Furtwangen im Schwarzwald',
 'Fürstenau',
 'Fürstenberg/Havel',
 'Fürstenfeldbruck',
 'Fürstenwalde/Spree',
 'Fürth',
 'Füssen',
 'Gadebusch',
 'Gaggenau',
 'Gaildorf',
 'Gammertingen',
 'Garbsen',
 'Garching bei München',
 'Gardelegen',
 'Garding',
 'Gartz (Oder)',
 'Garz/Rügen',
 'Gau-Algesheim',
 'Gebesee',
 'Gedern',
 'Geesthacht',
 'Geestland',
 'Gefell',
 'Gefrees',
 'Gehrden',
 'Geilenkirchen',
 'Geisa',
 'Geiselhöring',
 'Geisenfeld',
 'Geisenheim',
 'Geisingen',
 'Geislingen',
 'Geislingen an der Steige',
 'Geithain',
 'Geldern',
 'Gelnhausen',
 'Gelsenkirchen',
 'Gemünden (Wohra)',
 'Gemünden am Main',
 'Gengenbach',
 'Genthin',
 'Georgsmarienhütte',
 'Gera',
 'Gerabronn',
 'Gerbstedt',
 'Geretsried',
 'Geringswalde',
 'Gerlingen',
 'Germering',
 'Germersheim',
 'Gernsbach',
 'Gernsheim',
 'Gerolstein',
 'Gerolzhofen',
 'Gersfeld (Rhön)',
 'Gersthofen',
 'Gescher',
 'Geseke',
 'Gevelsberg',
 'Geyer',
 'Giengen an der Brenz',
 'Gießen',
 'Gifhorn',
 'Ginsheim-Gustavsburg',
 'Gladbeck',
 'Gladenbach',
 'Glashütte',
 'Glauchau',
 'Glinde',
 'Glücksburg (Ostsee)',
 'Glückstadt',
 'Gnoien',
 'Goch',
 'Goldberg',
 'Goldkronach',
 'Golßen',
 'Gommern',
 'Goslar',
 'Gotha',
 'Grabow',
 'Grafenau',
 'Grafenwöhr',
 'Grafing bei München',
 'Gransee',
 'Grebenau',
 'Grebenstein',
 'Greding',
 'Greifswald',
 'Greiz',
 'Greußen',
 'Greven',
 'Grevenbroich',
 'Grevesmühlen',
 'Griesheim',
 'Grimma',
 'Grimmen',
 'Groitzsch',
 'Gronau (Leine)',
 'Gronau (Westf.)',
 'Groß-Bieberau',
 'Groß-Gerau',
 'Groß-Umstadt',
 'Großalmerode',
 'Großbottwar',
 'Großbreitenbach',
 'Großenhain',
 'Großräschen',
 'Großröhrsdorf',
 'Großschirma',
 'Gräfenberg',
 'Gräfenhainichen',
 'Gräfenthal',
 'Gröditz',
 'Gröningen',
 'Grünberg',
 'Grünhain-Beierfeld',
 'Grünsfeld',
 'Grünstadt',
 'Guben',
 'Gudensberg',
 'Gummersbach',
 'Gundelfingen an der Donau',
 'Gundelsheim',
 'Gunzenhausen',
 'Göppingen',
 'Görlitz',
 'Göttingen',
 'Gößnitz',
 'Güglingen',
 'Günzburg',
 'Güsten',
 'Güstrow',
 'Gütersloh',
 'Gützkow',
 'Haan',
 'Haar',
 'Hachenburg',
 'Hadamar',
 'Hagen',
 'Hagenbach',
 'Hagenow',
 'Haiger',
 'Haigerloch',
 'Hainichen',
 'Haiterbach',
 'Halberstadt',
 'Haldensleben',
 'Halle (Saale)',
 'Halle (Westf.)',
 'Hallenberg',
 'Hallstadt',
 'Haltern am See',
 'Halver',
 'Hamburg',
 'Hameln',
 'Hamm',
 'Hammelburg',
 'Hamminkeln',
 'Hanau',
 'Hann. Münden',
 'Harburg (Schwaben)',
 'Hardegsen',
 'Haren (Ems)',
 'Harsewinkel',
 'Hartenstein',
 'Hartha',
 'Harzgerode',
 'Haselünne',
 'Haslach im Kinzigtal',
 'Hattersheim am Main',
 'Hattingen',
 'Hatzfeld (Eder)',
 'Hausach',
 'Hauzenberg',
 'Havelberg',
 'Havelsee',
 'Hayingen',
 'Haßfurt',
 'Hechingen',
 'Hecklingen',
 'Heide',
 'Heideck',
 'Heidelberg',
 'Heidenau',
 'Heidenheim an der Brenz',
 'Heilbad Heiligenstadt',
 'Heilbronn',
 'Heiligenhafen',
 'Heiligenhaus',
 'Heilsbronn',
 'Heimbach',
 'Heimsheim',
 'Heinsberg',
 'Heitersheim',
 'Heldburg',
 'Helmbrechts',
 'Helmstedt',
 'Hemau',
 'Hemer',
 'Hemmingen',
 'Hemmoor',
 'Hemsbach',
 'Hennef (Sieg)',
 'Hennigsdorf',
 'Heppenheim (Bergstraße)',
 'Herbolzheim',
 'Herborn',
 'Herbrechtingen',
 'Herbstein',
 'Herdecke',
 'Herdorf',
 'Herford',
 'Heringen (Werra)',
 'Heringen/Helme',
 'Hermeskeil',
 'Hermsdorf',
 'Herne',
 'Herrenberg',
 'Herrieden',
 'Herrnhut',
 'Hersbruck',
 'Herten',
 'Herzberg (Elster)',
 'Herzberg am Harz',
 'Herzogenaurach',
 'Herzogenrath',
 'Hessisch Lichtenau',
 'Hessisch Oldendorf',
 'Hettingen',
 'Hettstedt',
 'Heubach',
 'Heusenstamm',
 'Hilchenbach',
 'Hildburghausen',
 'Hilden',
 'Hildesheim',
 'Hillesheim',
 'Hilpoltstein',
 'Hirschau',
 'Hirschberg',
 'Hirschhorn (Neckar)',
 'Hitzacker (Elbe)',
 'Hochheim am Main',
 'Hockenheim',
 'Hof',
 'Hofgeismar',
 'Hofheim am Taunus',
 'Hofheim in Unterfranken',
 'Hohen Neuendorf',
 'Hohenberg an der Eger',
 'Hohenleuben',
 'Hohenmölsen',
 'Hohenstein-Ernstthal',
 'Hohnstein',
 'Hollfeld',
 'Holzgerlingen',
 'Holzminden',
 'Homberg (Efze)',
 'Homberg (Ohm)',
 'Homburg',
 'Horb am Neckar',
 'Horn-Bad Meinberg',
 'Hornbach',
 'Hornberg',
 'Horstmar',
 'Hoya',
 'Hoyerswerda',
 'Hungen',
 'Husum',
 'Höchstadt an der Aisch',
 'Höchstädt an der Donau',
 'Höhr-Grenzhausen',
 'Hörstel',
 'Höxter',
 'Hückelhoven',
 'Hückeswagen',
 'Hüfingen',
 'Hünfeld',
 'Hürth',
 'Ibbenbüren',
 'Ichenhausen',
 'Idar-Oberstein',
 'Idstein',
 'Illertissen',
 'Ilmenau',
 'Ilsenburg (Harz)',
 'Ilshofen',
 'Immenhausen',
 'Immenstadt im Allgäu',
 'Ingelfingen',
 'Ingelheim am Rhein',
 'Ingolstadt',
 'Iphofen',
 'Iserlohn',
 'Isny im Allgäu',
 'Isselburg',
 'Itzehoe',
 'Jarmen',
 'Jena',
 'Jerichow',
 'Jessen (Elster)',
 'Jever',
 'Joachimsthal',
 'Johanngeorgenstadt',
 'Jöhstadt',
 'Jüchen',
 'Jülich',
 'Jüterbog',
 'Kaarst',
 'Kahla',
 'Kaisersesch',
 'Kaiserslautern',
 'Kalbe (Milde)',
 'Kalkar',
 'Kaltenkirchen',
 'Kaltennordheim',
 'Kamen',
 'Kamenz',
 'Kamp-Lintfort',
 'Kandel',
 'Kandern',
 'Kappeln',
 'Karben',
 'Karlsruhe',
 'Karlstadt',
 'Kassel',
 'Kastellaun',
 'Katzenelnbogen',
 'Kaub',
 'Kaufbeuren',
 'Kehl',
 'Kelbra (Kyffhäuser)',
 'Kelheim',
 'Kelkheim (Taunus)',
 'Kellinghusen',
 'Kelsterbach',
 'Kemberg',
 'Kemnath',
 'Kempen',
 'Kempten (Allgäu)',
 'Kenzingen',
 'Kerpen',
 'Ketzin/Havel',
 'Kevelaer',
 'Kierspe',
 'Kirchberg',
 'Kirchberg (Hunsrück)',
 'Kirchberg an der Jagst',
 'Kirchen (Sieg)',
 'Kirchenlamitz',
 'Kirchhain',
 'Kirchheim unter Teck',
 'Kirchheimbolanden',
 'Kirn',
 'Kirtorf',
 'Kitzingen',
 'Kitzscher',
 'Kleve',
 'Klingenberg am Main',
 'Klingenthal',
 'Klötze',
 'Klütz',
 'Knittlingen',
 'Koblenz',
 'Kolbermoor',
 'Konstanz',
 'Konz',
 'Korbach',
 'Korntal-Münchingen',
 'Kornwestheim',
 'Korschenbroich',
 'Kraichtal',
 'Krakow am See',
 'Kranichfeld',
 'Krautheim',
 'Krefeld',
 'Kremmen',
 'Krempe',
 'Kreuztal',
 'Kronach',
 'Kronberg im Taunus',
 'Kroppenstedt',
 'Krumbach (Schwaben)',
 'Kröpelin',
 'Kulmbach',
 'Kupferberg',
 'Kuppenheim',
 'Kusel',
 'Kyllburg',
 'Kyritz',
 'Kölleda',
 'Köln',
 'Königs Wusterhausen',
 'Königsberg in Bayern',
 'Königsbrunn',
 'Königsbrück',
 'Königsee',
 'Königslutter am Elm',
 'Königstein (Sächsische Schweiz)',
 'Königstein im Taunus',
 'Königswinter',
 'Könnern',
 'Köthen (Anhalt)',
 'Kühlungsborn',
 'Külsheim',
 'Künzelsau',
 'Laage',
 'Laatzen',
 'Ladenburg',
 'Lage',
 'Lahnstein',
 'Lahr/Schwarzwald',
 'Laichingen',
 'Lambrecht (Pfalz)',
 'Lampertheim',
 'Landau an der Isar',
 'Landau in der Pfalz',
 'Landsberg',
 'Landsberg am Lech',
 'Landshut',
 'Landstuhl',
 'Langelsheim',
 'Langen',
 'Langenau',
 'Langenburg',
 'Langenfeld (Rheinland)',
 'Langenhagen',
 'Langenselbold',
 'Langenzenn',
 'Lassan',
 'Laubach',
 'Laucha an der Unstrut',
 'Lauchhammer',
 'Lauchheim',
 'Lauda-Königshofen',
 'Lauenburg/Elbe',
 'Lauf an der Pegnitz',
 'Laufen',
 'Laufenburg (Baden)',
 'Lauffen am Neckar',
 'Lauingen (Donau)',
 'Laupheim',
 'Lauscha',
 'Lauta',
 'Lauter-Bernsbach',
 'Lauterbach',
 'Lauterecken',
 'Lauterstein',
 'Lebach',
 'Lebus',
 'Leer (Ostfriesland)',
 'Lehesten',
 'Lehrte',
 'Leichlingen (Rheinland)',
 'Leimen',
 'Leinefelde-Worbis',
 'Leinfelden-Echterdingen',
 'Leingarten',
 'Leipheim',
 'Leipzig',
 'Leisnig',
 'Lemgo',
 'Lengenfeld',
 'Lengerich',
 'Lennestadt',
 'Lenzen (Elbe)',
 'Leonberg',
 'Leun',
 'Leuna',
 'Leutenberg',
 'Leutershausen',
 'Leutkirch im Allgäu',
 'Leverkusen',
 'Lich',
 'Lichtenau',
 'Lichtenberg',
 'Lichtenfels',
 'Lichtenstein/Sa.',
 'Liebenau',
 'Liebenwalde',
 'Lieberose',
 'Liebstadt',
 'Limbach-Oberfrohna',
 'Limburg an der Lahn',
 'Lindau (Bodensee)',
 'Linden',
 'Lindenberg im Allgäu',
 'Lindenfels',
 'Lindow (Mark)',
 'Lingen (Ems)',
 'Linnich',
 'Linz am Rhein',
 'Lippstadt',
 'Lohmar',
 'Lohne (Oldenburg)',
 'Lohr am Main',
 'Loitz',
 'Lollar',
 'Lommatzsch',
 'Lorch',
 'Lorsch',
 'Lucka',
 'Luckau',
 'Luckenwalde',
 'Ludwigsburg',
 'Ludwigsfelde',
 'Ludwigshafen am Rhein',
 'Ludwigslust',
 'Ludwigsstadt',
 'Lugau',
 'Lunzenau',
 'Lychen',
 'Löbau',
 'Löffingen',
 'Löhne',
 'Löningen',
 'Lörrach',
 'Löwenstein',
 'Lößnitz',
 'Lübbecke',
 'Lübben (Spreewald)',
 'Lübbenau/Spreewald',
 'Lübeck',
 'Lübtheen',
 'Lübz',
 'Lüchow (Wendland)',
 'Lüdenscheid',
 'Lüdinghausen',
 'Lügde',
 'Lüneburg',
 'Lünen',
 'Lütjenburg',
 'Lützen',
 'Magdala',
 'Mahlberg',
 'Mainbernheim',
 'Mainburg',
 'Maintal',
 'Malchin',
 'Malchow',
 'Manderscheid',
 'Mannheim',
 'Mansfeld',
 'Marbach am Neckar',
 'Marburg',
 'Marienberg',
 'Marienmünster',
 'Markdorf',
 'Markgröningen',
 'Markkleeberg',
 'Markneukirchen',
 'Markranstädt',
 'Marktbreit',
 'Marktheidenfeld',
 'Marktleuthen',
 'Marktoberdorf',
 'Marktredwitz',
 'Marktsteft',
 'Marl',
 'Marlow',
 'Marne',
 'Marsberg',
 'Maulbronn',
 'Maxhütte-Haidhof',
 'Mayen',
 'Mechernich',
 'Meckenheim',
 'Medebach',
 'Meerane',
 'Meerbusch',
 'Meersburg',
 'Meinerzhagen',
 'Meiningen',
 'Meisenheim',
 'Meißen',
 'Meldorf',
 'Melle',
 'Mellrichstadt',
 'Melsungen',
 'Memmingen',
 'Menden (Sauerland)',
 'Mendig',
 'Mengen',
 'Meppen',
 'Merkendorf',
 'Merseburg',
 'Merzig',
 'Meschede',
 'Mettmann',
 'Metzingen',
 'Meuselwitz',
 'Meyenburg',
 'Meßkirch',
 'Meßstetten',
 'Michelstadt',
 'Miesbach',
 'Miltenberg',
 'Mindelheim',
 'Minden',
 'Mirow',
 'Mittenwalde',
 'Mitterteich',
 'Mittweida',
 'Moers',
 'Monheim',
 'Monheim am Rhein',
 'Monschau',
 'Montabaur',
 'Moosburg an der Isar',
 'Moringen',
 'Mosbach',
 'Munderkingen',
 'Munster',
 'Murrhardt',
 'Märkisch Buchholz',
 'Möckern',
 'Möckmühl',
 'Mölln',
 'Mönchengladbach',
 'Mörfelden-Walldorf',
 'Mössingen',
 'Mücheln (Geiseltal)',
 'Mügeln',
 'Mühlacker',
 'Mühlberg/Elbe',
 'Mühldorf am Inn',
 'Mühlhausen/Thüringen',
 'Mühlheim am Main',
 'Mühlheim an der Donau',
 'Mülheim an der Ruhr',
 'Mülheim-Kärlich',
 'Müllheim im Markgräflerland',
 'Müllrose',
 'Münchberg',
 'Müncheberg',
 'Münchenbernsdorf',
 'Münnerstadt',
 'Münsingen',
 'Münster',
 'Münstermaifeld',
 'Münzenberg',
 'Nabburg',
 'Nagold',
 'Naila',
 'Nassau',
 'Nastätten',
 'Nauen',
 'Naumburg',
 'Naumburg (Saale)',
 'Naunhof',
 'Nebra (Unstrut)',
 'Neckarbischofsheim',
 'Neckargemünd',
 'Neckarsteinach',
 'Neckarsulm',
 'Neresheim',
 'Netphen',
 'Nettetal',
 'Netzschkau',
 'Neu-Anspach',
 'Neu-Isenburg',
 'Neu-Ulm',
 'Neubrandenburg',
 'Neubukow',
 'Neubulach',
 'Neuburg an der Donau',
 'Neudenau',
 'Neuenburg am Rhein',
 'Neuenbürg',
 'Neuenhaus',
 'Neuenrade',
 'Neuenstadt am Kocher',
 'Neuenstein',
 'Neuerburg',
 'Neuffen',
 'Neuhaus am Rennweg',
 'Neukalen',
 'Neukirchen',
 'Neukirchen-Vluyn',
 'Neukloster',
 'Neumark',
 'Neumarkt in der Oberpfalz',
 'Neumarkt-Sankt Veit',
 'Neumünster',
 'Neunburg vorm Wald',
 'Neunkirchen',
 'Neuruppin',
 'Neusalza-Spremberg',
 'Neuss',
 'Neustadt (Dosse)',
 'Neustadt (Hessen)',
 'Neustadt am Kulm',
 'Neustadt am Rübenberge',
 'Neustadt an der Aisch',
 'Neustadt an der Donau',
 'Neustadt an der Orla',
 'Neustadt an der Waldnaab',
 'Neustadt an der Weinstraße',
 'Neustadt bei Coburg',
 'Neustadt in Holstein',
 'Neustadt in Sachsen',
 'Neustadt-Glewe',
 'Neustrelitz',
 'Neusäß',
 'Neutraubling',
 'Neuwied',
 'Neuötting',
 'Nidda',
 'Niddatal',
 'Nidderau',
 'Nideggen',
 'Niebüll',
 'Niedenstein',
 'Nieder-Olm',
 'Niederkassel',
 'Niedernhall',
 'Niederstetten',
 'Niederstotzingen',
 'Nieheim',
 'Niemegk',
 'Nienburg (Saale)',
 'Nienburg/Weser',
 'Nierstein',
 'Niesky',
 'Nittenau',
 'Norden',
 'Nordenham',
 'Norderney',
 'Norderstedt',
 'Nordhausen',
 'Nordhorn',
 'Northeim',
 'Nortorf',
 'Nossen',
 'Nottertal-Heilinger Höhen',
 'Nördlingen',
 'Nürnberg',
 'Nürtingen',
 'Ober-Ramstadt',
 'Oberasbach',
 'Oberderdingen',
 'Oberharz am Brocken',
 'Oberhausen',
 'Oberhof',
 'Oberkirch',
 'Oberkochen',
 'Oberlungwitz',
 'Obermoschel',
 'Obernburg am Main',
 'Oberndorf am Neckar',
 'Obernkirchen',
 'Oberriexingen',
 'Obertshausen',
 'Oberursel (Taunus)',
 'Oberviechtach',
 'Oberwesel',
 'Oberwiesenthal',
 'Oberzent',
 'Ochsenfurt',
 'Ochsenhausen',
 'Ochtrup',
 'Oderberg',
 'Oebisfelde-Weferlingen',
 'Oederan',
 'Oelde',
 'Oelsnitz/Erzgeb.',
 'Oelsnitz/Vogtl.',
 'Oer-Erkenschwick',
 'Oerlinghausen',
 'Oestrich-Winkel',
 'Oettingen in Bayern',
 'Offenbach am Main',
 'Offenburg',
 'Ohrdruf',
 'Olbernhau',
 'Olching',
 'Oldenburg (Oldb)',
 'Oldenburg in Holstein',
 'Olfen',
 'Olpe',
 'Olsberg',
 'Oppenau',
 'Oppenheim',
 'Oranienbaum-Wörlitz',
 'Oranienburg',
 'Orlamünde',
 'Ornbau',
 'Ortenberg',
 'Ortrand',
 'Oschatz',
 'Oschersleben (Bode)',
 'Osnabrück',
 'Osterburg (Altmark)',
 'Osterburken',
 'Osterfeld',
 'Osterhofen',
 'Osterholz-Scharmbeck',
 'Osterode am Harz',
 'Osterwieck',
 'Ostfildern',
 'Ostheim vor der Rhön',
 'Osthofen',
 'Ostritz',
 'Otterberg',
 'Otterndorf',
 'Ottweiler',
 'Overath',
 'Owen',
 'Paderborn',
 'Papenburg',
 'Pappenheim',
 'Parchim',
 'Parsberg',
 'Pasewalk',
 'Passau',
 'Pattensen',
 'Pausa-Mühltroff',
 'Pegau',
 'Pegnitz',
 'Peine',
 'Peitz',
 'Penig',
 'Penkun',
 'Penzberg',
 'Penzlin',
 'Perleberg',
 'Petershagen',
 'Pfaffenhofen an der Ilm',
 'Pfarrkirchen',
 'Pforzheim',
 'Pfreimd',
 'Pfullendorf',
 'Pfullingen',
 'Pfungstadt',
 'Philippsburg',
 'Pinneberg',
 'Pirmasens',
 'Pirna',
 'Plattling',
 'Plau am See',
 'Plaue',
 'Plauen',
 'Plettenberg',
 'Pleystein',
 'Plochingen',
 'Plön',
 'Pockau-Lengefeld',
 'Pocking',
 'Pohlheim',
 'Polch',
 'Porta Westfalica',
 'Pottenstein',
 'Preetz',
 'Premnitz',
 'Prenzlau',
 'Pressath',
 'Preußisch Oldendorf',
 'Prichsenstadt',
 'Pritzwalk',
 'Prüm',
 'Puchheim',
 'Pulheim',
 'Pulsnitz',
 'Putbus',
 'Putlitz',
 'Pößneck',
 'Püttlingen',
 'Quakenbrück',
 'Quedlinburg',
 'Querfurt',
 'Quickborn',
 'Rabenau',
 'Radeberg',
 'Radebeul',
 'Radeburg',
 'Radevormwald',
 'Radolfzell am Bodensee',
 'Raguhn-Jeßnitz',
 'Rahden',
 'Rain',
 'Ramstein-Miesenbach',
 'Ranis',
 'Ransbach-Baumbach',
 'Rastatt',
 'Rastenberg',
 'Rathenow',
 'Ratingen',
 'Ratzeburg',
 'Rauenberg',
 'Raunheim',
 'Rauschenberg',
 'Ravensburg',
 'Ravenstein',
 'Recklinghausen',
 'Rees',
 'Regen',
 'Regensburg',
 'Regis-Breitingen',
 'Rehau',
 'Rehburg-Loccum',
 'Rehna',
 'Reichelsheim (Wetterau)',
 'Reichenbach im Vogtland',
 'Reichenbach/O.L.',
 'Reinbek',
 'Reinfeld (Holstein)',
 'Reinheim',
 'Remagen',
 'Remscheid',
 'Remseck am Neckar',
 'Renchen',
 'Rendsburg',
 'Rennerod',
 'Renningen',
 'Rerik',
 'Rethem (Aller)',
 'Reutlingen',
 'Rheda-Wiedenbrück',
 'Rhede',
 'Rheinau',
 'Rheinbach',
 'Rheinberg',
 'Rheinböllen',
 'Rheine',
 'Rheinfelden (Baden)',
 'Rheinsberg',
 'Rheinstetten',
 'Rhens',
 'Rhinow',
 'Ribnitz-Damgarten',
 'Richtenberg',
 'Riedenburg',
 'Riedlingen',
 'Riedstadt',
 'Rieneck',
 'Riesa',
 'Rietberg',
 'Rinteln',
 'Rochlitz',
 'Rockenhausen',
 'Rodalben',
 'Rodenberg',
 'Rodewisch',
 'Rodgau',
 'Roding',
 'Romrod',
 'Ronneburg',
 'Ronnenberg',
 'Rosbach vor der Höhe',
 'Rosenfeld',
 'Rosenheim',
 'Rosenthal',
 'Rostock',
 'Rotenburg (Wümme)',
 'Rotenburg an der Fulda',
 'Roth',
 'Rothenburg ob der Tauber',
 'Rothenburg/O.L.',
 'Rothenfels',
 'Rottenburg a.d.Laaber',
 'Rottenburg am Neckar',
 'Rottweil',
 'Roßleben-Wiehe',
 'Roßwein',
 'Rudolstadt',
 'Ruhla',
 'Ruhland',
 'Runkel',
 'Rutesheim',
 'Röbel/Müritz',
 'Rödental',
 'Rödermark',
 'Römhild',
 'Rösrath',
 'Rötha',
 'Röthenbach an der Pegnitz',
 'Röttingen',
 'Rötz',
 'Rüdesheim am Rhein',
 'Rüsselsheim am Main',
 'Rüthen',
 'Saalburg-Ebersdorf',
 'Saalfeld/Saale',
 'Saarburg',
 'Saarlouis',
 'Sachsenhagen',
 'Sachsenheim',
 'Salzgitter',
 'Salzkotten',
 'Salzwedel',
 'Sandau (Elbe)',
 'Sandersdorf-Brehna',
 'Sangerhausen',
 'Sankt Augustin',
 'Sankt Goar',
 'Sankt Goarshausen',
 'Sarstedt',
 'Sassenberg',
 'Sassnitz',
 'Sayda',
 'Schalkau',
 'Schauenstein',
 'Scheer',
 'Scheibenberg',
 'Scheinfeld',
 'Schelklingen',
 'Schenefeld',
 'Scheßlitz',
 'Schieder-Schwalenberg',
 'Schifferstadt',
 'Schillingsfürst',
 'Schiltach',
 'Schirgiswalde-Kirschau',
 'Schkeuditz',
 'Schkölen',
 'Schleiden',
 'Schleiz',
 'Schleswig',
 'Schlettau',
 'Schleusingen',
 'Schlieben',
 'Schlitz',
 'Schloß Holte-Stukenbrock',
 'Schlüchtern',
 'Schlüsselfeld',
 'Schmalkalden',
 'Schmallenberg',
 'Schmölln',
 'Schnackenburg',
 'Schnaittenbach',
 'Schneeberg',
 'Schneverdingen',
 'Schongau',
 'Schopfheim',
 'Schorndorf',
 'Schortens',
 'Schotten',
 'Schramberg',
 'Schraplau',
 'Schriesheim',
 'Schrobenhausen',
 'Schrozberg',
 'Schwaan',
 'Schwabach',
 'Schwabmünchen',
 'Schwaigern',
 'Schwalbach am Taunus',
 'Schwalmstadt',
 'Schwandorf',
 'Schwanebeck',
 'Schwarzatal',
 'Schwarzenbach am Wald',
 'Schwarzenbach an der Saale',
 'Schwarzenbek',
 'Schwarzenberg/Erzgeb.',
 'Schwarzenborn',
 'Schwarzheide',
 'Schwedt/Oder',
 'Schweich',
 'Schweinfurt',
 'Schwelm',
 'Schwentinental',
 'Schwerte',
 'Schwetzingen',
 'Schwäbisch Gmünd',
 'Schwäbisch Hall',
 'Schömberg',
 'Schönau',
 'Schönau im Schwarzwald',
 'Schönberg',
 'Schönebeck (Elbe)',
 'Schöneck/Vogtl.',
 'Schönewalde',
 'Schöningen',
 'Schönsee',
 'Schönwald',
 'Schöppenstedt',
 'Schüttorf',
 'Sebnitz',
 'Seehausen (Altmark)',
 'Seeland',
 'Seelow',
 'Seelze',
 'Seesen',
 'Sehnde',
 'Seifhennersdorf',
 'Selb',
 'Selbitz',
 'Seligenstadt',
 'Selm',
 'Selters (Westerwald)',
 'Senden',
 'Sendenhorst',
 'Senftenberg',
 'Seßlach',
 'Siegburg',
 'Siegen',
 'Sigmaringen',
 'Simbach am Inn',
 'Simmern/Hunsrück',
 'Sindelfingen',
 'Singen (Hohentwiel)',
 'Sinsheim',
 'Sinzig',
 'Soest',
 'Solingen',
 'Solms',
 'Soltau',
 'Sondershausen',
 'Sonneberg',
 'Sonnewalde',
 'Sonthofen',
 'Sontra',
 'Spaichingen',
 'Spalt',
 'Spangenberg',
 'Speicher',
 'Spenge',
 'Speyer',
 'Spremberg',
 'Springe',
 'Sprockhövel',
 'St. Blasien',
 'St. Georgen im Schwarzwald',
 'St. Ingbert',
 'St. Wendel',
 'Stade',
 'Stadt Wehlen',
 'Stadtallendorf',
 'Stadtbergen',
 'Stadthagen',
 'Stadtilm',
 'Stadtlohn',
 'Stadtoldendorf',
 'Stadtprozelten',
 'Stadtroda',
 'Stadtsteinach',
 'Starnberg',
 'Staufen im Breisgau',
 'Staufenberg',
 'Stavenhagen',
 'Staßfurt',
 'Stein',
 'Steinach',
 'Steinau an der Straße',
 'Steinbach (Taunus)',
 'Steinbach-Hallenberg',
 'Steinfurt',
 'Steinheim',
 'Steinheim an der Murr',
 'Stendal',
 'Sternberg',
 'Stockach',
 'Stolberg (Rheinland)',
 'Stollberg/Erzgeb.',
 'Stolpen',
 'Storkow (Mark)',
 'Straelen',
 'Stralsund',
 'Strasburg (Uckermark)',
 'Straubing',
 'Strausberg',
 'Strehla',
 'Stromberg',
 'Stutensee',
 'Stößen',
 'Stühlingen',
 'Suhl',
 'Sulingen',
 'Sulz am Neckar',
 'Sulzbach-Rosenberg',
 'Sulzbach/Saar',
 'Sulzburg',
 'Sundern (Sauerland)',
 'Syke',
 'Sömmerda',
 'Südliches Anhalt',
 'Süßen',
 'Tambach-Dietharz',
 'Tamm',
 'Tangerhütte',
 'Tangermünde',
 'Tann (Rhön)',
 'Tanna',
 'Tauberbischofsheim',
 'Taucha',
 'Taunusstein',
 'Tecklenburg',
 'Tegernsee',
 'Telgte',
 'Teltow',
 'Templin',
 'Tengen',
 'Tessin',
 'Teterow',
 'Tettnang',
 'Teublitz',
 'Teuchern',
 'Teupitz',
 'Teuschnitz',
 'Thale',
 'Thalheim/Erzgeb.',
 'Thannhausen',
 'Tharandt',
 'Themar',
 'Thum',
 'Tirschenreuth',
 'Titisee-Neustadt',
 'Tittmoning',
 'Todtnau',
 'Torgau',
 'Torgelow',
 'Tornesch',
 'Traben-Trarbach',
 'Traunreut',
 'Traunstein',
 'Trebbin',
 'Trebsen/Mulde',
 'Treffurt',
 'Trendelburg',
 'Treuchtlingen',
 'Treuen',
 'Treuenbrietzen',
 'Triberg im Schwarzwald',
 'Tribsees',
 'Trier',
 'Triptis',
 'Trochtelfingen',
 'Troisdorf',
 'Trossingen',
 'Trostberg',
 'Tuttlingen',
 'Twistringen',
 'Töging am Inn',
 'Tönisvorst',
 'Tönning',
 'Tübingen',
 'Uebigau-Wahrenbrück',
 'Ueckermünde',
 'Uelzen',
 'Uetersen',
 'Uffenheim',
 'Uhingen',
 'Ulm',
 'Ulmen',
 'Ulrichstein',
 'Ummerstadt',
 'Unkel',
 'Unna',
 'Unterschleißheim',
 'Usedom',
 'Usingen',
 'Uslar',
 'Vacha',
 'Vaihingen an der Enz',
 'Vallendar',
 'Varel',
 'Vechta',
 'Velbert',
 'Velburg',
 'Velden',
 'Velen',
 'Vellberg',
 'Vellmar',
 'Velten',
 'Verden (Aller)',
 'Veringenstadt',
 'Verl',
 'Versmold',
 'Vetschau/Spreewald',
 'Viechtach',
 'Viernheim',
 'Viersen',
 'Villingen-Schwenningen',
 'Vilsbiburg',
 'Vilseck',
 'Vilshofen an der Donau',
 'Visselhövede',
 'Vlotho',
 'Voerde (Niederrhein)',
 'Vogtsburg im Kaiserstuhl',
 'Vohburg an der Donau',
 'Vohenstrauß',
 'Volkach',
 'Volkmarsen',
 'Vreden',
 'Vöhrenbach',
 'Vöhringen',
 'Völklingen',
 'Wachenheim an der Weinstraße',
 'Wadern',
 'Waghäusel',
 'Wahlstedt',
 'Waiblingen',
 'Waibstadt',
 'Waischenfeld',
 'Waldbröl',
 'Waldeck',
 'Waldenbuch',
 'Waldenburg',
 'Waldershof',
 'Waldheim',
 'Waldkappel',
 'Waldkirch',
 'Waldkirchen',
 'Waldkraiburg',
 'Waldmohr',
 'Waldmünchen',
 'Waldsassen',
 'Waldshut-Tiengen',
 'Walldorf',
 'Walldürn',
 'Wallenfels',
 'Walsrode',
 'Waltershausen',
 'Waltrop',
 'Wanfried',
 'Wangen im Allgäu',
 'Wanzleben-Börde',
 'Warburg',
 'Waren (Müritz)',
 'Warendorf',
 'Warin',
 'Warstein',
 'Wassenberg',
 'Wasserburg am Inn',
 'Wassertrüdingen',
 'Wasungen',
 'Wedel',
 'Weener',
 'Wegberg',
 'Wegeleben',
 'Wehr',
 'Weida',
 'Weiden in der Oberpfalz',
 'Weikersheim',
 'Weil am Rhein',
 'Weil der Stadt',
 'Weilburg',
 'Weilheim an der Teck',
 'Weilheim in Oberbayern',
 'Weimar',
 'Weingarten',
 'Weinheim',
 'Weinsberg',
 'Weinstadt',
 'Weismain',
 'Weiterstadt',
 'Weißenberg',
 'Weißenburg in Bayern',
 'Weißenfels',
 'Weißenhorn',
 'Weißensee',
 'Weißenthurm',
 'Weißwasser/O.L.',
 'Welzheim',
 'Welzow',
 'Wemding',
 'Wendlingen am Neckar',
 'Werben (Elbe)',
 'Werdau',
 'Werder (Havel)',
 'Werdohl',
 'Werl',
 'Werlte',
 'Wermelskirchen',
 'Wernau (Neckar)',
 'Werne',
 'Werneuchen',
 'Wernigerode',
 'Werra-Suhl-Tal',
 'Wertheim',
 'Werther (Westf.)',
 'Wertingen',
 'Wesel',
 'Wesenberg',
 'Wesselburen',
 'Wesseling',
 'Westerburg',
 'Westerstede',
 'Wetter (Hessen)',
 'Wetter (Ruhr)',
 'Wettin-Löbejün',
 'Wetzlar',
 'Widdern',
 'Wiehl',
 'Wiesensteig',
 'Wiesloch',
 'Wiesmoor',
 'Wildau',
 'Wildberg',
 'Wildenfels',
 'Wildeshausen',
 'Wilhelmshaven',
 'Wilkau-Haßlau',
 'Willebadessen',
 'Willich',
 'Wilsdruff',
 'Wilster',
 'Wilthen',
 'Windischeschenbach',
 'Windsbach',
 'Winnenden',
 'Winsen (Luhe)',
 'Winterberg',
 'Wipperfürth',
 'Wirges',
 'Wismar',
 'Wissen',
 'Witten',
 'Wittenberg',
 'Wittenberge',
 'Wittenburg',
 'Wittichenau',
 'Wittingen',
 'Wittlich',
 'Wittmund',
 'Wittstock/Dosse',
 'Witzenhausen',
 'Woldegk',
 'Wolfach',
 'Wolfenbüttel',
 'Wolfhagen',
 'Wolframs-Eschenbach',
 'Wolfratshausen',
 'Wolfsburg',
 'Wolfstein',
 'Wolgast',
 'Wolkenstein',
 'Wolmirstedt',
 'Worms',
 'Wriezen',
 'Wunsiedel',
 'Wunstorf',
 'Wuppertal',
 'Wurzbach',
 'Wurzen',
 'Wustrow (Wendland)',
 'Wyk auf Föhr',
 'Wächtersbach',
 'Wörrstadt',
 'Wörth am Main',
 'Wörth am Rhein',
 'Wörth an der Donau',
 'Wülfrath',
 'Würselen',
 'Würzburg',
 'Xanten',
 'Zahna-Elster',
 'Zarrentin am Schaalsee',
 'Zehdenick',
 'Zeil am Main',
 'Zeitz',
 'Zell (Mosel)',
 'Zell am Harmersbach',
 'Zell im Wiesental',
 'Zella-Mehlis',
 'Zerbst/Anhalt',
 'Zeulenroda-Triebes',
 'Zeven',
 'Ziegenrück',
 'Zierenberg',
 'Ziesar',
 'Zirndorf',
 'Zittau',
 'Zossen',
 'Zschopau',
 'Zweibrücken',
 'Zwenkau',
 'Zwickau',
 'Zwiesel',
 'Zwingenberg',
 'Zwönitz',
 'Zörbig',
 'Zülpich',
 'Öhringen',
 'Östringen',
 'Übach-Palenberg',
 'Überlingen']
# 1.1.0 Beta5.1
